export const HISTORY_REAL_WORLD_EXAMPLES = {
  'us-government': [
    {title:'Plessy v Ferguson, 1896',example:'The US Supreme Court upheld racial segregation under the “separate but equal” doctrine. The ruling helped give constitutional protection to segregation for decades.',demonstrates:'Federal institutions could preserve inequality as well as challenge it. Comparing Plessy with Brown shows why the Supreme Court’s influence changed across the period rather than remaining consistently progressive.'},
    {title:'Brown v Board of Education, 1954',example:'The Supreme Court ruled state-sponsored segregation in public schools unconstitutional, declaring that “separate educational facilities are inherently unequal”.',demonstrates:'Constitutional interpretation could overturn a long-standing legal settlement. Brown was a major legal turning point, but a court ruling did not automatically produce immediate integration in every state.'},
    {title:'Little Rock, 1957',example:'When Arkansas resisted school desegregation at Central High School, President Eisenhower federalised the Arkansas National Guard and sent federal troops to enforce the court order.',demonstrates:'Federalism could produce direct conflict between state and national authority. Supreme Court decisions sometimes required presidential enforcement before legal change became practical change.'},
    {title:'Civil Rights Act 1964 and Voting Rights Act 1965',example:'Congress passed major federal legislation under President Johnson. The Civil Rights Act prohibited discrimination in major public and employment settings, while the Voting Rights Act attacked discriminatory voting practices and strengthened federal enforcement.',demonstrates:'Change often depended on interaction between activists, presidents and Congress. No single institution explains the scale of mid-1960s civil-rights reform.'}
  ],
  'civil-rights': [
    {title:'Jim Crow and the Plessy settlement',example:'By the early twentieth century segregation and disfranchisement were entrenched across much of the South, while Plessy v Ferguson provided constitutional support for “separate but equal”.',demonstrates:'The depth of the starting inequality matters when judging later progress. Civil-rights change should be measured against the strength and durability of the system it challenged.'},
    {title:'The Great Migration',example:'From the 1910s to 1970, millions of African Americans moved from the South to northern and western cities. World War I employment opportunities, rail links, Jim Crow and racial violence all contributed.',demonstrates:'Civil-rights change did not begin in the 1950s. Migration changed jobs, voting strength, communities and political influence while discrimination continued in new forms.'},
    {title:'NAACP legal campaigning',example:'The NAACP used federal courts over decades to challenge disfranchisement, housing segregation and unequal education before the Brown decision of 1954.',demonstrates:'Brown was the result of a longer institutional strategy rather than an isolated court victory. Legal campaigning should be compared with grassroots protest and federal legislation.'},
    {title:'Double V Campaign and World War II',example:'During the Second World War, the Double V campaign linked victory over fascism overseas with victory over racism at home. The NAACP supported the campaign as wartime mobilisation increased pressure against discrimination.',demonstrates:'The war exposed contradictions between American war aims and domestic segregation. It acted as a catalyst for activism but was not the only cause of post-war civil-rights change.'},
    {title:'Montgomery Bus Boycott, 1955-1956',example:'Rosa Parks’ arrest helped trigger a boycott involving around 17,000 Black residents. The campaign lasted more than a year and combined grassroots organisation, economic pressure and legal challenge.',demonstrates:'Local mobilisation could produce practical change. Parks was already an activist, so the boycott should not be reduced to one spontaneous individual action.'},
    {title:'Brown to federal legislation',example:'Brown challenged school segregation in 1954. A decade later the Civil Rights Act 1964 prohibited discrimination much more widely, and the Voting Rights Act 1965 strengthened political rights.',demonstrates:'The strongest explanation is cumulative: courts, protest, Congress and presidents reinforced one another. A single turning point can be important without explaining the whole process.'},
    {title:'Voting Rights Act, 1965',example:'The Act outlawed discriminatory voting practices such as literacy tests and provided stronger federal mechanisms to protect registration and voting rights.',demonstrates:'Formal rights required enforcement. Selma, national publicity, presidential leadership and congressional action all contributed to the scale of the change.'},
    {title:'Civil rights after 1968',example:'The WJEC theme continues to 1990 because legal desegregation and voting rights did not remove every economic, residential, educational or political inequality. Black Power, affirmative action and urban unrest remained important.',demonstrates:'1964-65 can be a major legal turning point without being the end of the story. Formal equality and lived equality must be distinguished.'}
  ],
  'superpower': [
    {title:'Spanish-American War, 1898',example:'US victory over Spain brought Puerto Rico, Guam and the Philippines under American control or sovereignty and strengthened US influence in Cuba and the Pacific.',demonstrates:'The USA was already projecting power overseas before 1900. This is strong evidence against treating all pre-1941 foreign policy as simple isolationism.'},
    {title:'Panama Canal, 1903-1914',example:'The Hay-Bunau-Varilla Treaty gave the USA control of a canal zone and the completed canal transformed strategic and commercial movement between the Atlantic and Pacific.',demonstrates:'US power combined military, commercial, technological and geopolitical strength. Superpower development was gradual rather than beginning only in 1945.'},
    {title:'World War I and Wilson’s Fourteen Points',example:'The USA entered the First World War in 1917. Wilson then promoted a “just and secure peace” and proposed a League of Nations as part of the Fourteen Points.',demonstrates:'Military entry and Wilsonian diplomacy showed growing international ambition, while later refusal to join the League reveals the limits of that internationalist turn.'},
    {title:'Lend-Lease before Pearl Harbor',example:'Before formal US entry into the Second World War, Roosevelt expanded support for Britain and other Allies through Lend-Lease and related measures.',demonstrates:'Legal neutrality did not mean complete detachment. US foreign policy was changing before December 1941, making the transition from isolation to engagement more gradual than a single-date explanation suggests.'},
    {title:'Truman Doctrine, 1947',example:'Truman asked Congress for aid to Greece and Turkey and declared a policy to “support free peoples who are resisting attempted subjugation”.',demonstrates:'Containment marked a major acceptance of continuing global commitments. The USA was willing to use economic and military support to shape political outcomes far beyond the Western Hemisphere.'},
    {title:'Marshall Plan, 1948',example:'The United States committed $13.3 billion over four years to European recovery after the Second World War, supporting reconstruction, markets and political stability.',demonstrates:'Superpower status depended on economic as well as military power. American influence operated through aid, trade and institutions as well as armed force.'},
    {title:'Cuban Missile Crisis, 1962',example:'For thirteen days the USA and USSR confronted one another over Soviet nuclear missiles in Cuba, bringing the world close to nuclear war before a negotiated settlement.',demonstrates:'Superpower influence also created extreme global risk. Kennedy’s role should be judged through military strength, diplomacy, intelligence and Soviet decision-making together.'},
    {title:'Détente and arms control',example:'During the 1970s the USA and USSR pursued arms-control agreements and reduced some tensions, but rivalry continued and relations worsened again after the Soviet invasion of Afghanistan.',demonstrates:'Détente changed the method of superpower competition rather than ending it. Continuity and change can operate at the same time.'},
    {title:'Reagan, Gorbachev and the late Cold War',example:'Reagan publicly challenged Gorbachev to “tear down this wall”, while later summit diplomacy and the 1987 INF Treaty accompanied a rapid transformation in US-Soviet relations.',demonstrates:'Presidential leadership mattered, but the end of the Cold War also involved Gorbachev’s reforms, Soviet economic weakness and wider Eastern European change. Reagan alone is an insufficient explanation.'}
  ],
  'breadth-judgement': [
    {title:'Testing 1941 as a foreign-policy turning point',example:'Compare pre-war neutrality and Lend-Lease with wartime mobilisation, the Truman Doctrine, Marshall Plan and later permanent Cold War commitments.',demonstrates:'A turning point is strongest when change is large, durable and shapes later policy. The comparison prevents Pearl Harbor from becoming an isolated narrative event.'},
    {title:'Testing 1954-1965 as a civil-rights turning phase',example:'Place Brown, Montgomery, Little Rock, the Civil Rights Act and Voting Rights Act in one sequence rather than treating one event as the entire explanation.',demonstrates:'Some turning points are processes. Comparing courts, protest, presidents and Congress produces a stronger judgement about scale, pace and causation.'},
    {title:'Legal change versus lived change',example:'Compare Plessy-era legal exclusion with post-1968 economic, residential and educational inequalities after major civil-rights legislation had already passed.',demonstrates:'Change and continuity can coexist. Formal legal equality does not automatically prove that social outcomes changed at the same pace.'},
    {title:'Testing presidential importance across a century',example:'Compare Wilson, Roosevelt, Truman, Kennedy, Johnson, Nixon and Reagan with Congress, courts, activists, war, economic strength and Soviet decisions.',demonstrates:'A president may be decisive in one phase without being the single most important cause across the entire period. Breadth judgement requires criteria and comparison.'}
  ],
  'whig-reform': [
    {title:'Factory Act 1833',example:'The Act prohibited factory work for children under nine, limited hours for older children and created a small factory inspectorate. Initially only four inspectors covered thousands of mills.',demonstrates:'The state was taking a more direct role in industrial conditions, but passing legislation and enforcing it were different problems. Humanitarianism and administrative control can both be considered as motives.'},
    {title:'Poor Law Amendment Act 1834',example:'The Act reorganised poor relief under greater central control and encouraged workhouse provision designed to deter unnecessary claims and reduce costs.',demonstrates:'Reform did not always mean generosity. Efficiency, economy, utilitarian thinking and social control could drive change, while the measure itself became a cause of protest.'},
    {title:'Municipal Corporations Act 1835',example:'The Act replaced many unreformed municipal corporations with elected borough councils and began a more standardised structure of urban local government.',demonstrates:'Whig reform was administrative and political as well as humanitarian. Changes in local government also helped create machinery later used for public-health reform.'},
    {title:'Mines and Collieries Act 1842',example:'A Royal Commission exposed underground working conditions for women and children. Parliament then prohibited underground work for women and girls and boys under ten.',demonstrates:'Investigation and public exposure could generate political pressure. Reform was more likely when campaigning, evidence and parliamentary concern aligned.'},
    {title:'Factory Act 1844 and Ten Hours Act 1847',example:'Further legislation strengthened factory safety and working-hour limits, culminating in a ten-hour day for women and young people aged 13 to 18.',demonstrates:'The 1833 Act was an important beginning rather than a complete solution. Repeated legislation shows both continuity of reform and weaknesses in earlier enforcement.'},
    {title:'Chadwick and Public Health Act 1848',example:'Edwin Chadwick’s sanitary investigation linked disease, poor urban conditions and the costs of poverty. The Public Health Act 1848 created a national framework for local sanitary action.',demonstrates:'Humanitarian and economic motives could reinforce one another. Public health widened expectations about government responsibility for industrial towns.'}
  ],
  chartism: [
    {title:'The People’s Charter, 1838',example:'The Charter demanded universal male suffrage, secret ballots, equal constituencies, annual elections, payment of MPs and removal of the property qualification for MPs.',demonstrates:'Chartism had a clear political programme. Later reforms can be compared directly with the Six Points when judging its long-term significance.'},
    {title:'First Chartist petition, 1839',example:'The first national petition gathered more than 1.25 million signatures but was rejected by Parliament.',demonstrates:'Mass popular support did not translate directly into parliamentary power. Rejection intensified debate over strategy and helps explain later unrest.'},
    {title:'Newport Rising, 1839',example:'Thousands of Chartists marched into Newport under leaders including John Frost. Troops at the Westgate Hotel opened fire and at least 22 protesters were killed.',demonstrates:'South Wales was central to national Chartist history. Newport shows both the depth of support and the state’s capacity to defeat armed protest, but it does not prove all Chartists favoured violence.'},
    {title:'Second petition, 1842',example:'The 1842 Chartist petition carried about 3.3 million signatures and declared the principle that “all should be equally represented”, yet Parliament again rejected the Charter.',demonstrates:'Chartism could mobilise extraordinary national support. Numerical support alone could not overcome parliamentary resistance or political exclusion.'},
    {title:'Plug Plot disturbances, 1842',example:'Workers in industrial districts stopped machinery by removing boiler plugs during strikes associated with wage cuts, hardship and strong Chartist support.',demonstrates:'Political and economic grievances could overlap. Chartist support rose during periods of economic pressure, so movement strength cannot be explained by political ideas alone.'},
    {title:'Kennington Common and the third petition, 1848',example:'The 1848 demonstration attracted far fewer people than organisers hoped. Parliament disputed the claimed petition total and the movement rapidly lost momentum.',demonstrates:'Government preparation, economic context, organisational weakness and public expectations all matter when explaining decline. Failure should not be reduced to one cause.'},
    {title:'Chartist legacy',example:'By 1918, five of the Six Points had effectively been achieved, although Parliament had not simply accepted Chartism in the 1840s.',demonstrates:'Immediate failure and long-term significance are different judgements. Later reform should not automatically be credited to Chartism without tracing the historical connection.'}
  ],
  'protest-wales-england': [
    {title:'Opposition to the New Poor Law',example:'The 1834 Poor Law reforms centralised relief and encouraged workhouses designed to deter claims, generating deep hostility in many communities.',demonstrates:'Government reform could itself create protest. Resistance reflected material hardship, local autonomy and moral objections to the new principles of relief.'},
    {title:'Rebecca Riots, c.1839-1843',example:'The Daughters of Rebecca attacked tollgates in west and mid Wales. Tolls were the immediate target, but poverty, rents, tithes and resentment of local authority formed a wider background.',demonstrates:'Welsh rural protest had distinctive local and economic causes. Reducing Rebecca to tollgates alone misses the breadth of grievance and community support.'},
    {title:'Rebecca archival records',example:'The National Library of Wales preserves proclamations, reward notices, correspondence and prisoner records connected with the Rebecca disturbances.',demonstrates:'Different source types reveal different perspectives. Official records are strong evidence for state priorities and responses but may frame protesters mainly as criminals.'},
    {title:'Anti-Corn Law League',example:'The League used national organisation, meetings, print, petitions, fundraising and electoral pressure rather than the armed tactics seen at Newport or attacks on Rebecca tollgates.',demonstrates:'Movements differed in resources, social base and access to political influence. Methods must be evaluated alongside political opportunity and the interests of decision-makers.'},
    {title:'Corn Law repeal, 1846',example:'Peel’s government secured repeal after sustained Anti-Corn Law agitation and the Irish Famine. Cobden insisted that “no power on earth could prevent” repeal, but the decision also split the Conservative Party.',demonstrates:'Successful reform usually has several causes. Campaign pressure mattered, but crisis and leadership within government must be weighed alongside it.'}
  ],
  'source-evaluation': [
    {title:'War Office plan of the Westgate Hotel, 1839',example:'The National Archives holds a War Office plan showing troop positions and bodies during the Newport Rising.',demonstrates:'It is valuable for reconstructing official military positioning and the state record of the confrontation, but it cannot directly reveal the motives or experiences of ordinary Chartist marchers.'},
    {title:'The 1842 Chartist petition',example:'The petition records Chartist grievances and political demands and was presented with about 3.3 million signatures.',demonstrates:'It is highly valuable for declared aims and organisational scale, but signatures do not prove that every supporter shared identical motives or approved every Chartist tactic.'},
    {title:'Mines Commission evidence, 1842',example:'The Royal Commission publicised underground working conditions for women and children using testimony and vivid illustrations before the Mines and Collieries Act.',demonstrates:'The material is valuable for what Parliament and the public were being shown, while the investigators’ reform purpose and selection of evidence must still be considered.'},
    {title:'Rebecca proclamations and reward notices',example:'State records offered rewards, issued proclamations and documented prosecutions during the Rebecca disturbances.',demonstrates:'These sources reveal official fears, priorities and methods of control. Their state provenance may also encourage a criminal framing that under-represents local grievances.'},
    {title:'Cobden in parliamentary debate, 1846',example:'Cobden argued in Parliament for complete repeal of the Corn Laws and presented the Anti-Corn Law campaign as powerful, persistent and legitimate.',demonstrates:'The speech is direct evidence of campaign strategy and rhetoric. As a leading campaigner speaking during a decisive political struggle, Cobden also had a clear persuasive purpose.'}
  ],
  'nea-process': [
    {title:'Building a primary-source log',example:'For each letter, government report, newspaper, speech, map, photograph or archive record, record creator, date, provenance, relevance, useful evidence and limitations as research happens.',demonstrates:'Primary does not mean automatically true or unbiased. Source value depends on the exact enquiry and on what the source can reasonably establish.'},
    {title:'Recording historians’ interpretations',example:'For each historian, record the central argument, evidence used, scope, assumptions and how the interpretation agrees or conflicts with another historian rather than collecting isolated quotations.',demonstrates:'Unit 5 requires engagement with interpretations as arguments. A quotation is useful only when Kellyn understands the historian’s reasoning and tests it against evidence.'},
    {title:'WJEC Unit 5 boundaries',example:'The historical enquiry is 3,000 to 4,000 words, must follow the approved title process and is assessed across knowledge, source evaluation and interpretations.',demonstrates:'Kellyn Hub can support planning, source organisation and understanding of method, but the assessed historical argument and submitted prose must remain Kellyn’s own work.'}
  ]
}
