export const EXTRA_DEPTH = {
  sociology: {
    'crime-social-construction': {
      depth: [
        'Go beyond the basic distinction between crime and deviance by asking how formal law and informal social norms are produced. Parliament, courts, police, schools, families, media organisations and peer groups can all influence what is defined as acceptable or unacceptable behaviour.',
        'Becker’s labelling approach is useful because it shifts attention from the act itself to the social reaction. His idea of moral entrepreneurs highlights that some groups have greater power to create rules and campaign for their enforcement. This helps explain why definitions of deviance can reflect unequal power.',
        'Lemert’s distinction between primary and secondary deviance helps explain how a label can affect identity. Primary deviance may be limited and have little effect on self-concept, while repeated social reaction may encourage a person to accept a deviant identity and become more involved in deviant behaviour.',
        'Stanley Cohen’s study of Mods and Rockers shows how media reporting can contribute to a moral panic. Exaggeration, prediction and symbolisation can increase public concern, which may then encourage stronger social-control responses.',
        'Social construction does not mean crime is unreal. Victimisation and harm can be very real. The sociological point is that societies differ in which harmful acts are criminalised, how seriously they are treated and which groups receive the greatest attention from agencies of control.'
      ],
      evidence: ['Becker: deviance is linked to rule creation and the application of labels.', 'Lemert: primary and secondary deviance.', 'Stanley Cohen: moral panic, folk devils, exaggeration and amplification.', 'Compare historical or cross-cultural changes in law to show that definitions are not fixed.'],
      analysis: ['Who benefits from a particular definition of deviance?', 'Does labelling explain the original act or the response that follows it?', 'Can media reaction increase social control without the underlying level of behaviour increasing?', 'How would a Marxist explanation of rule-making differ from an interactionist one?']
    },
    'crime-patterns-measurement': {
      depth: [
        'Official crime data are created through a process rather than simply discovered. An incident must occur, be recognised as an offence, become known to the police and be recorded under counting rules. Attrition at each stage helps explain the hidden figure of crime.',
        'Victimisation surveys can provide a broader picture because they ask people about experiences whether or not those incidents were reported. Their strengths include access to unreported crime and repeat victimisation, but limitations include memory, willingness to disclose and the exclusion of some offence types.',
        'Self-report studies ask respondents about offences they have committed. They are particularly useful for examining less serious or undetected offending, but the sample, wording of questions, honesty and recall of participants can all affect validity.',
        'Patterns by class, gender, ethnicity and age need separate description and explanation. A recorded difference could reflect actual offending, exposure to victimisation, police deployment, reporting behaviour, surveillance, stereotypes, opportunity or differences in the types of offences committed.',
        'A strong sociological interpretation uses more than one data source. If official statistics and victim surveys show similar patterns, confidence may increase. If they differ, the difference itself becomes something to explain.'
      ],
      evidence: ['Cicourel: official statistics can reflect processes of negotiation, typification and police decision-making.', 'The hidden figure includes crime that is not reported, detected or recorded.', 'Victim surveys and police-recorded crime measure different things and should not be treated as interchangeable.', 'Use recent ONS or Welsh Government data supplied by school to anchor current patterns.'],
      analysis: ['What exactly is being measured?', 'Could the method itself create part of the pattern?', 'Is a social-group difference evidence of offending, enforcement, victimisation or a mixture?', 'Would the same conclusion be reached using another source of data?']
    },
    'crime-theories': {
      depth: [
        'Durkheim argued that deviance is normal and inevitable because complete value consensus is impossible. Some deviance can reinforce boundaries when society reacts against it, while change in norms can also begin with behaviour initially defined as deviant.',
        'Merton’s strain theory links crime to the tension between culturally approved goals and unequal access to legitimate means. Innovation is the adaptation most directly linked to some forms of crime because the goal is accepted but illegitimate means are used.',
        'Cohen’s subcultural theory develops strain by focusing on status frustration among some working-class boys. Cloward and Ohlin add the idea that access to illegitimate opportunities also varies, producing different subcultural responses.',
        'Marxist approaches argue that capitalism shapes law and enforcement. Some laws protect private property and economic interests, while harms associated with powerful groups may receive different levels of attention. Neo-Marxist approaches such as Taylor, Walton and Young try to combine structural inequality with individual meaning and choice.',
        'Left realism takes the impact of crime on disadvantaged communities seriously and uses ideas such as relative deprivation, marginalisation and subculture. Right realism is more likely to focus on individual choice, weak controls, opportunity and deterrence.',
        'Feminist sociology highlights gendered patterns of offending, victimisation and control. Heidensohn examines social control of women, Carlen links female offending to class and gendered disadvantage, while Messerschmidt links some offending to ways of accomplishing masculinity.'
      ],
      evidence: ['Durkheim: boundary maintenance and the normality of deviance.', 'Merton: strain and adaptations including innovation.', 'Cohen: status frustration; Cloward and Ohlin: illegitimate opportunity structures.', 'Taylor, Walton and Young: neo-Marxist attempt at a fully social theory of deviance.', 'Lea and Young: relative deprivation, marginalisation and subculture.', 'Heidensohn, Carlen and Messerschmidt: contrasting gender explanations.'],
      analysis: ['Which theories explain the social distribution of crime best?', 'Which theory explains crimes of the powerful?', 'Does a theory explain motivation, opportunity, reaction or all three?', 'What evidence would distinguish one theory from another?']
    },
    'crime-policy-evaluation': {
      depth: [
        'Policies are built on assumptions about causes. Situational crime prevention assumes that reducing opportunity or increasing the effort and risk of offending can reduce crime. Target hardening, surveillance and environmental design are examples.',
        'Right-realist approaches may support deterrence, visible policing, stronger informal social controls and measures that increase the perceived cost of offending. Evaluation should ask whether crime falls, whether it is displaced and whether some communities experience disproportionate control.',
        'Left-realists are more likely to combine policing reform with action on relative deprivation, marginalisation and community relations. This can include multi-agency approaches and attempts to improve trust between police and communities.',
        'Interactionist ideas raise concern about unnecessary criminalisation because formal intervention can strengthen labels and secondary deviance. Diversion or restorative approaches can therefore be linked to attempts to reduce damaging labelling.',
        'Policy evaluation needs outcome evidence, not only good intentions. Consider effectiveness, cost, fairness, displacement, unintended consequences and whether the policy changes underlying behaviour or merely recorded levels of crime.'
      ],
      evidence: ['Situational prevention: reduce opportunities and increase perceived risk.', 'Labelling theory supports caution about unnecessary formal intervention.', 'Left realism links policy to deprivation, marginalisation, victimisation and police-community relations.', 'Feminist evaluation asks whether policy recognises domestic and sexual violence and other gendered harms.'],
      analysis: ['What theory of causation sits behind the policy?', 'How would success actually be measured?', 'Could displacement make the policy look more successful than it is?', 'Are effectiveness and fairness pointing in the same direction?']
    },
    'methods-design': {
      depth: [
        'Operationalisation is the bridge between an abstract idea and research evidence. If the research question includes concepts such as achievement, deprivation, identity or fear of crime, the researcher must decide how those ideas will be recognised or measured.',
        'Questionnaires can generate comparable data from larger samples, while interviews can produce greater depth. Observations allow behaviour to be studied in context, and documents or existing statistics can give access to evidence that would be difficult to collect directly.',
        'Sampling should be judged by the research aim. Random and systematic approaches can support representativeness when a sampling frame exists. Stratified sampling can ensure important groups are represented. Snowball and purposive sampling may be more suitable for hidden or specialised populations.',
        'Reliability concerns consistency and replicability, while validity concerns whether the evidence genuinely captures the phenomenon being studied. Standardisation may improve reliability but sometimes reduce depth or ecological validity.',
        'Ethical planning should cover informed consent, deception, right to withdraw, confidentiality, anonymity, privacy, safeguarding and protection from harm. With vulnerable participants, the practical meaning of informed consent needs particular care.',
        'Triangulation uses more than one method or source to examine an issue. It can provide complementary forms of evidence, but disagreement between methods should be analysed rather than hidden.'
      ],
      evidence: ['Probability sampling supports statistical generalisation when implemented well.', 'Non-probability methods can be justified when access is difficult or a specialist sample is required.', 'Reliability and validity can pull in different directions depending on method design.', 'Pilot studies can identify unclear questions, practical problems and likely weaknesses before main data collection.'],
      analysis: ['What kind of data does the research question actually require?', 'What is lost as well as gained by choosing this method?', 'Which limitation has the greatest effect on the conclusions?', 'How could the design be adjusted without creating a new problem?']
    },
    'inequality-patterns': {
      depth: [
        'Social inequality concerns unequal life chances, resources, status and power. Social class, gender, ethnicity and age may each shape outcomes, but they also intersect. A person can occupy several advantaged and disadvantaged social positions at the same time.',
        'Income is money received over a period, while wealth is the stock of assets such as property, savings and investments. Wealth is usually distributed more unequally than income and can be transferred between generations.',
        'Education can reproduce or reduce inequality through attainment, subject choices, access to resources, expectations and progression. Employment inequalities can appear in pay, occupational status, security, promotion and unemployment risk.',
        'Health inequalities can be examined through life expectancy, healthy life expectancy, long-term illness and access to resources that support wellbeing. Sociologists ask whether observed differences arise from material conditions, behaviour, culture, services or measurement.',
        'Mobility evidence needs careful interpretation. Absolute mobility can rise because the occupational structure changes even when relative chances between social classes remain unequal.'
      ],
      evidence: ['Use ONS and Welsh Government measures for contemporary income, employment, education and health patterns.', 'Distinguish wealth from income in every explanation.', 'Use more than one indicator before claiming a group is generally advantaged or disadvantaged.', 'Intersectionality helps explain why broad categories do not describe everybody within them equally well.'],
      analysis: ['Does the pattern persist after another factor is considered?', 'Is the measure showing resources, outcomes or opportunities?', 'What mechanism could plausibly create this inequality?', 'Does the evidence support structural or individual explanations more strongly?']
    },
    'inequality-theories': {
      depth: [
        'Davis and Moore argue that stratification can perform functions by encouraging people to train for and fill socially important roles. Critics question whether the most highly rewarded roles are necessarily the most important and whether unequal starting points undermine the idea of merit.',
        'Marx locates class inequality in ownership of the means of production and the relationship between capital and labour. Later Marxists give greater attention to the state, culture, ideology and the complexity of modern class structures.',
        'Weber provides a multidimensional approach by separating class, status and party. People can therefore share a similar economic position but differ in prestige or political influence. Neo-Weberian writers develop ideas of market situation and social closure.',
        'Feminist explanations examine patriarchy, occupational segregation, unpaid domestic labour, caring responsibilities and gendered power. Different feminist perspectives disagree over the relative importance of capitalism, patriarchy, culture and individual choice.',
        'New Right arguments often emphasise incentives, markets and personal responsibility, while postmodern approaches question whether large class categories capture increasingly diverse identities and lifestyles.',
        'Strong evaluation tests each theory against patterns. A theory that explains one form of inequality well may be weaker on another, so avoid treating a single perspective as an explanation of every social difference.'
      ],
      evidence: ['Davis and Moore: functional necessity and differential reward.', 'Marx: ownership, class conflict and exploitation.', 'Weber: class, status and party; social closure can restrict opportunities.', 'Feminist approaches: patriarchy, paid work, unpaid labour and gendered institutions.', 'New Right and postmodern approaches offer contrasting interpretations of agency and contemporary diversity.'],
      analysis: ['Which theory best explains persistence across generations?', 'Does the theory explain gender and ethnicity as well as class?', 'How much inequality can be explained by markets and how much by institutions?', 'What contemporary evidence most clearly challenges the theory?']
    }
  },
  law: {
    'criminal-liability': {
      depth: [
        'Begin every criminal problem by identifying the possible offence and then proving each element. The prosecution normally bears the legal burden and must prove guilt beyond reasonable doubt. Some specific defences can place an evidential or legal burden on the defendant.',
        'Actus reus can consist of conduct, circumstances, a consequence or an omission. Liability for an omission is exceptional and normally requires a recognised duty, such as a contractual duty, a duty arising from a relationship, voluntary assumption of care or creation of a dangerous situation.',
        'For result crimes, factual causation uses the but-for test. Legal causation then considers whether the defendant’s conduct was more than a minimal cause and remained an operating and substantial cause. Medical treatment, victim conduct and third-party acts can raise questions about whether the chain of causation is broken.',
        'Mens rea must match the offence. Direct intention means the consequence is the defendant’s aim or purpose. Oblique intention may be inferred where the consequence was virtually certain and the defendant appreciated that virtual certainty. Subjective recklessness concerns conscious awareness of an unjustified risk.',
        'The coincidence principle normally requires actus reus and mens rea to exist at the same time. Courts sometimes use continuing-act or single-transaction reasoning where a sequence of events would otherwise create an artificial gap.',
        'Strict liability removes the need to prove mens rea for at least one element. It is often justified by regulation and public protection but criticised because liability can be imposed despite limited fault.'
      ],
      evidence: ['R v White: but-for factual causation.', 'R v Pagett: legal causation and third-party response.', 'R v Blaue: thin-skull principle and victim characteristics.', 'R v Woollin: virtual certainty direction for oblique intention.', 'R v G: subjective recklessness.', 'Gammon v A-G of Hong Kong: presumption of mens rea and approach to strict liability.'],
      analysis: ['Which exact element is disputed?', 'Is causation factual, legal or both?', 'What fact proves awareness of risk or intention?', 'Would a strict-liability interpretation promote protection at the expense of fault?']
    },
    'criminal-offences-defences': {
      depth: [
        'Homicide requires precise classification. Murder is unlawful killing with the required mens rea, while voluntary manslaughter begins with murder but reduces liability where a qualifying partial defence applies. Involuntary manslaughter includes unlawful-act manslaughter and gross-negligence manslaughter, which have different tests.',
        'For non-fatal offences, distinguish assault, battery, ABH and the section 18 and section 20 offences under the Offences Against the Person Act 1861. The seriousness of injury and the required mens rea are not identical across the offences.',
        'Theft under the Theft Act 1968 requires appropriation of property belonging to another, dishonesty and intention permanently to deprive. Robbery requires a completed theft plus force or threat of force used immediately before or at the time of stealing and in order to steal.',
        'Burglary has two main statutory routes under section 9 of the Theft Act 1968. Always identify which route the facts suggest because entry, trespass, intention and the later offence are treated differently.',
        'General defences should be learned as separate tests. Self-defence focuses on the defendant’s belief in the need for force and whether the force used was reasonable in the circumstances as believed. Intoxication, insanity, automatism and duress each have distinct requirements and limitations.',
        'Attempt liability under the Criminal Attempts Act 1981 requires intent for the full offence and an act that is more than merely preparatory. A defendant can be liable even where completion was factually impossible if the statutory requirements are met.'
      ],
      evidence: ['Theft Act 1968: theft, robbery and burglary.', 'Offences Against the Person Act 1861: key non-fatal offences.', 'Criminal Attempts Act 1981: attempt and more-than-merely-preparatory test.', 'Use the homicide and defence authorities identified in Kellyn’s WJEC materials to support each element rather than listing cases separately.'],
      analysis: ['Which offence most closely fits the injury, property or conduct proved?', 'Have all statutory elements been applied?', 'Does the defence completely acquit or reduce the offence?', 'What alternative offence remains if one element cannot be proved?']
    },
    'human-rights-framework': {
      depth: [
        'The European Convention on Human Rights is an international treaty. The Human Rights Act 1998 makes Convention rights directly relevant in UK courts while preserving the constitutional position that Parliament remains able to enact legislation.',
        'Section 2 requires UK courts to take Strasbourg jurisprudence into account. Section 3 requires legislation, so far as possible, to be read compatibly with Convention rights. Where that is not possible, higher courts may issue a declaration of incompatibility under section 4 rather than striking down the Act of Parliament.',
        'Section 6 makes it unlawful for public authorities to act incompatibly with Convention rights unless primary legislation requires the incompatible action. Section 7 allows a victim of an unlawful act to bring proceedings or rely on Convention rights in existing proceedings.',
        'Rights have different structures. Article 3 is absolute. Rights such as Article 8, Article 10 and Article 11 are qualified and can be restricted where the interference is lawful, pursues a legitimate aim and is necessary and proportionate in a democratic society.',
        'Article 5 protects liberty and security but permits detention in specified lawful circumstances. Article 6 protects the right to a fair hearing. Article 8 covers private and family life, home and correspondence. Article 10 protects expression, including ideas that may offend or disturb, subject to lawful limitations.',
        'Proportionality requires more than asking whether the government has a good reason. The measure must pursue a legitimate objective, be rationally connected to it, interfere no more than reasonably necessary and strike a fair balance between individual rights and community interests.',
        'Human-rights analysis often requires a sequence: identify the protected right, decide whether there is an interference, identify the legal basis and legitimate aim, then test necessity and proportionality. This prevents vague discussion of fairness from replacing legal reasoning.'
      ],
      evidence: ['Human Rights Act 1998 sections 2, 3, 4, 6 and 7 are central to the domestic framework.', 'Article 3 is absolute; Articles 8, 10 and 11 are qualified rights.', 'Article 5 protects liberty; Article 6 fair hearing; Article 8 private/family life; Article 10 expression.', 'Use case law to show how courts balance rights and competing public interests, not simply to memorise outcomes.'],
      analysis: ['Is the right absolute, limited or qualified?', 'Has there actually been an interference with the right?', 'What legitimate aim is relied upon?', 'Is a less intrusive measure realistically available?', 'How does the HRA balance judicial protection of rights with parliamentary sovereignty?']
    },
    'law-evaluation': {
      depth: [
        'For Criminal Law, evaluation can focus on fault, certainty, fairness, public protection and whether old legislation still provides a coherent framework. The continuing use of the Offences Against the Person Act 1861 is a clear example of a statute whose language and structure can be criticised as outdated.',
        'Strict liability raises a classic conflict between efficient regulation and individual fault. It can make enforcement easier and encourage high standards, but it may punish a defendant who took reasonable care.',
        'Human Rights evaluation should consider whether the Human Rights Act gives courts sufficient tools. Section 3 can enable rights-compatible interpretation, while section 4 respects parliamentary sovereignty but leaves the incompatible legislation legally valid until political action is taken.',
        'Rights themselves can conflict. Freedom of expression may conflict with privacy; protest rights may conflict with public order; liberty may conflict with public protection. Strong evaluation identifies the legal mechanism used to balance those interests.',
        'Law reform arguments need criteria. Ask whether the present law is clear, accessible, consistent, fair, enforceable, rights-compliant and capable of producing predictable outcomes. Then compare reform options against the same criteria.'
      ],
      evidence: ['OAPA 1861 provides material for evaluation of clarity and modernisation.', 'Strict liability illustrates the tension between fault and regulatory effectiveness.', 'HRA sections 3 and 4 illustrate the relationship between judicial interpretation and parliamentary sovereignty.', 'Proportionality provides a structured way to evaluate state interference with qualified rights.'],
      analysis: ['What principle is the current rule trying to protect?', 'Does the rule produce predictable outcomes?', 'Would reform solve the identified problem or create a new one?', 'Whose interests gain or lose under the current approach?']
    }
  },
  history: {
    'us-government': {
      depth: ['Federalism divides authority between federal and state governments, while separation of powers divides federal authority between executive, legislature and judiciary. This creates multiple points at which reform can be advanced, delayed or blocked.', 'The President can shape policy through leadership, appointments and executive action, but Congress controls legislation and finance. The Supreme Court can interpret the Constitution and federal law, while states retain substantial authority in areas that changed across the period.', 'For historical explanation, institutions matter because the balance of power changes with elections, court decisions, war, economic crisis and public pressure. Avoid treating “the government” as one actor with one view.', 'When studying civil rights, reform or foreign policy, identify which institution had the legal power to act and which political conditions made action possible.'],
      evidence: ['Federal and state powers can conflict, especially in civil-rights history.', 'Presidential leadership is constrained by Congress, courts, elections and federalism.', 'Supreme Court decisions can create major legal turning points but implementation may depend on other institutions.'],
      analysis: ['Which institution had the power to make the change?', 'Was the main obstacle constitutional, political or social?', 'Did a legal decision create immediate practical change?']
    },
    'civil-rights': {
      depth: ['Treat civil rights as a century-long process. The period includes segregation, disfranchisement and racial violence, but also legal challenge, mass mobilisation, federal intervention and changing national attitudes.', 'Early twentieth-century organisations such as the NAACP used litigation and campaigning. Mid-century change accelerated through court decisions, grassroots activism and federal action, but resistance from states and local authorities remained significant.', 'Brown v Board of Education in 1954 was a major legal turning point, yet desegregation was uneven. The Civil Rights Act 1964 and Voting Rights Act 1965 strengthened federal protection, while later decades raised questions about economic equality, policing and the limits of legal reform.', 'A strong judgement separates legal equality from social and economic outcomes. Progress can be substantial in one dimension while continuity remains in another.'],
      evidence: ['Plessy v Ferguson provides context for legally sanctioned segregation before the period of major federal reform.', 'Brown v Board of Education 1954 challenged segregated public schooling.', 'Civil Rights Act 1964 and Voting Rights Act 1965 are major federal legislative turning points.', 'Grassroots activism, court action, presidential leadership and congressional action should be compared rather than studied separately.'],
      analysis: ['Which mattered more at each stage: activists, courts, presidents or Congress?', 'Was 1965 a decisive turning point or part of a longer process?', 'How far did legal change alter lived experience?']
    },
    'superpower': {
      depth: ['In 1890 the USA already had major economic potential, but becoming a global superpower involved expansion of military, diplomatic and financial influence as well as industrial growth.', 'The Spanish-American War and acquisition of overseas influence marked a more assertive role. The First World War demonstrated growing economic and military capacity, although interwar policy still contained strong reluctance toward permanent political commitments.', 'The Second World War transformed the international balance. The USA emerged with enormous industrial capacity, global military reach and a central role in new international institutions. The Cold War then embedded long-term political, military and ideological leadership.', 'By 1990, superpower status rested not only on military strength but on finance, technology, alliances, cultural influence and the relative weakening or collapse of rivals.'],
      evidence: ['Spanish-American War 1898 as evidence of expanding overseas power.', 'US role in the First World War and interwar retreat should be compared.', 'Second World War mobilisation and post-1945 institutions mark a major expansion of global influence.', 'Cold War alliances, nuclear capability and economic power sustained superpower status.'],
      analysis: ['Was economic power the foundation for military power?', 'Which war changed the USA’s international role most decisively?', 'How continuous was isolationism before 1941?']
    },
    'breadth-judgement': {
      depth: ['Breadth questions reward command of the whole period. Start by defining the criterion for judgement, such as scale of change, durability, geographical reach, impact on different groups or importance compared with other factors.', 'Chronological coverage should be selective rather than mechanical. Choose evidence from different parts of the period that directly tests the proposition in the question.', 'Turning points are strongest when you explain both what changed and what did not. A dramatic event is not automatically the most significant if its effects were temporary or limited.', 'Build judgement throughout rather than saving it for the conclusion. Each paragraph should compare the evidence against the same criteria so the final conclusion follows logically.'],
      evidence: ['Use examples from early, middle and later parts of the period.', 'A turning point must be judged by impact and durability, not drama alone.', 'Counter-evidence is necessary to test the claimed extent of change.'],
      analysis: ['What criteria make one development more significant than another?', 'Is the argument true across the whole period?', 'Which evidence most seriously challenges the provisional judgement?']
    },
    'whig-reform': {
      depth: ['The 1832 Reform Act widened representation but did not create democracy. Many working-class men remained excluded, constituencies and voting rights remained unequal, and political disappointment helped sustain later reform movements.', 'Whig reform after 1832 included changes to poor relief, factories, municipal government and other areas. Each reform should be linked to the problem ministers thought they were addressing and the administrative machinery created to implement it.', 'The 1834 Poor Law Amendment Act illustrates tensions between economy, deterrence and humanitarian claims. Factory legislation illustrates the gradual growth of state intervention in industrial conditions, although inspection and enforcement could be limited.', 'Interpretation matters: reform can be explained through humanitarian pressure, fear of disorder, administrative efficiency, economic ideas and political calculation. Different measures may have different balances of motive.'],
      evidence: ['1832 Reform Act left substantial political exclusion.', 'Poor Law Amendment Act 1834 changed the administration of relief.', 'Factory reform demonstrates expanding concern with industrial conditions and enforcement.', 'Municipal reform can be used to examine administrative modernisation.'],
      analysis: ['Was reform mainly humanitarian or designed for order and efficiency?', 'How effectively was legislation implemented?', 'Which groups benefited and which experienced new restrictions?']
    },
    'chartism': {
      depth: ['The People’s Charter set out six political demands and gave Chartism a recognisable national programme. Its support nevertheless varied greatly by region and over time.', 'Chartist strategy included petitions, mass meetings, organisation, print culture and debate over moral-force and physical-force methods. These differences reflected disagreement over how pressure should be applied rather than the absence of common aims.', 'Economic downturns often strengthened support because unemployment, wage pressure and insecurity made political exclusion feel more urgent. Improved economic conditions could reduce mobilisation.', 'The rejection of petitions and state repression contributed to immediate failure, but longer-term significance can be judged through political education, working-class organisation and the later adoption of several Charter demands.'],
      evidence: ['People’s Charter 1838 as the movement’s programme.', 'National petitions demonstrate mass mobilisation but also parliamentary rejection.', 'Newport Rising 1839 is especially relevant to Welsh experience and state response.', 'Later reform eventually adopted several demands, though not because of Chartism alone.'],
      analysis: ['Was internal division more important than government strength?', 'How closely did support track economic conditions?', 'Can a movement be historically significant despite immediate failure?']
    },
    'protest-wales-england': {
      depth: ['Popular protest should be explained through the interaction of economic pressure, local grievances, political exclusion and community organisation. Avoid treating every movement as simply a response to poverty.', 'In Wales, the Rebecca Riots provide a strong case study of local grievance, turnpike tolls, rural hardship and symbolic collective action. The Newport Rising connects Welsh protest directly to Chartism and political reform.', 'Government response could involve policing, troops, arrest, prosecution, transportation or investigation followed by limited reform. The type of response often depended on the perceived threat to property and order.', 'Comparison is powerful: ask why some movements built national organisations while others remained regionally rooted, and why different tactics produced different levels of support or repression.'],
      evidence: ['Rebecca Riots: tollgates, rural grievance and direct action in Wales.', 'Newport Rising 1839: armed Chartist confrontation and severe state response.', 'Compare petitioning, mass meetings and direct action as different protest repertoires.'],
      analysis: ['Which grievance mobilised participants most strongly?', 'Did repression end the grievance or only the protest?', 'Why did some protests remain local while Chartism became national?']
    },
    'source-evaluation': {
      depth: ['Value depends on the enquiry. Start with the source’s content and identify precisely what it reveals about the issue being investigated.', 'Use contextual knowledge to test accuracy, identify what is omitted and explain references that a modern reader might otherwise miss. Context should interact with the source rather than appear as a separate factual paragraph.', 'Provenance is useful when author, audience, purpose, timing or circumstances affect what can be learned. A partisan speech may be weak evidence of neutral fact but excellent evidence of political priorities or rhetoric.', 'Avoid the automatic claim that bias makes a source useless. Historians often learn most from partial sources when the nature of that partiality is understood.'],
      evidence: ['Content, context and provenance should all relate to the exact enquiry.', 'Contemporary sources can reveal attitudes without necessarily providing accurate factual accounts.', 'Later recollections may benefit from hindsight but suffer from memory and retrospective justification.'],
      analysis: ['What can this source prove directly?', 'What can it reveal unintentionally?', 'How does contextual knowledge strengthen or weaken its claims?']
    },
    'nea-process': {
      depth: ['Treat the NEA as a managed enquiry rather than one long writing task. Keep the approved question visible and use it to decide whether each source, note and line of investigation is relevant.', 'Build an audit trail as research happens. Record bibliographic details, useful page numbers, short notes on argument and any quotations needed for later checking.', 'Separate collection from evaluation. A source can be relevant without being reliable, and historians can disagree because they use different evidence, concepts or interpretations.', 'Use supervisor feedback to decide the next action, but maintain authorship. Planning, research logs and version history help demonstrate an authentic process as well as keeping the enquiry manageable.'],
      evidence: ['Approved title and centre guidance control the assessed task.', 'A contemporaneous research log strengthens organisation and authentication.', 'Bibliographic details should be captured when the source is first used.'],
      analysis: ['How does this source help answer the exact enquiry?', 'What interpretation does it support or challenge?', 'What gap in the evidence should be researched next?']
    }
  },
  'welsh-bacc': {
    'question-rationale': {
      depth: ['A viable project question needs a clear focus, a genuine issue to investigate and enough credible evidence to support analysis. Questions that are too broad lead to description because the project cannot explore causes, perspectives or evidence in sufficient depth.', 'The rationale should explain the purpose of the enquiry, why the issue is worth investigating and what the project hopes to find out. It should not assume the conclusion in advance.', 'Aims describe the overall purpose; objectives break that purpose into smaller research intentions. Each objective should contribute directly to answering the project question.', 'Feasibility includes time, access to information, ethics, participant recruitment if primary research is proposed and whether the scope can be completed within the assessment requirements.'],
      evidence: ['A focused question gives the project a clear decision rule for what evidence is relevant.', 'Objectives should map directly onto the question rather than becoming a list of unrelated tasks.', 'Early ethical screening prevents a project design that later becomes unusable.'],
      analysis: ['Can the question genuinely be answered with available evidence?', 'Does the wording invite analysis rather than description?', 'What would make the project too broad to manage?']
    },
    'research-plan': {
      depth: ['A research plan should show sequence, dependencies and realistic time. Some tasks cannot begin until others are complete, so milestones should identify what must be finished before analysis and production begin.', 'Plan evidence needs before methods. Decide whether the project needs factual background, statistical evidence, expert interpretation, stakeholder experience or original primary data, then choose sources and methods capable of supplying it.', 'Primary research can add value but is not automatically better than secondary research. It must answer a genuine evidence need and be proportionate to the project.', 'Build contingency time into the plan. Access problems, slow responses, unusable sources and changes after supervisor feedback are normal research risks rather than exceptional failures.'],
      evidence: ['Milestones turn a large deadline into observable progress.', 'Method choice should follow the evidence need.', 'A contingency plan reduces the effect of predictable delays.'],
      analysis: ['Which task is on the critical path?', 'What evidence gap would stop the project answering its question?', 'What is the fallback if a planned source or participant becomes unavailable?']
    },
    'source-evaluation-ip': {
      depth: ['Evaluate authority by asking who produced the source, what expertise they have and whether the organisation has a reason to present the issue in a particular way.', 'Evaluate evidence by checking whether claims are supported with data, references, transparent methods or links to primary material. A professional-looking website is not evidence of reliability on its own.', 'Currency matters differently across topics. Recent statistics may be essential for a current issue, while older research may still be valuable for theory, historical context or comparison.', 'Triangulate important claims. If several independent high-quality sources agree, confidence may increase. If they disagree, identify whether the difference comes from method, definition, date, population or interpretation.'],
      evidence: ['Authority, evidence, currency, purpose and relevance are separate checks.', 'Original reports and official datasets are often stronger for factual claims than summaries of them.', 'Disagreement between credible sources should be investigated rather than averaged away.'],
      analysis: ['What evidence sits behind the claim?', 'Is the source independent of the claim it is promoting?', 'Would another credible source define or measure the issue differently?']
    },
    'analyse-evidence': {
      depth: ['Move from source-by-source notes to theme-based analysis. Put evidence addressing the same idea together so patterns and disagreements become visible.', 'Distinguish correlation from causation. Two factors moving together does not prove one caused the other, so look for mechanisms, alternative explanations and the design of the research producing the evidence.', 'Weight evidence rather than counting sources. One rigorous large study may be more persuasive than several weak opinion pieces. Explain why particular evidence deserves greater weight.', 'A conclusion should answer the project question at the level the evidence allows. Where evidence is mixed or limited, a qualified conclusion is stronger than an overconfident claim.'],
      evidence: ['Themes make synthesis easier than sequential summaries.', 'Method quality affects how much weight evidence should receive.', 'Limitations should change the strength of the conclusion, not simply be listed at the end.'],
      analysis: ['What pattern appears across the evidence?', 'Which evidence deserves the greatest weight and why?', 'What plausible alternative explanation remains?']
    },
    'produce-review': {
      depth: ['Production should communicate the investigation clearly and in the required format. Structure should follow the project question and analysis rather than the order in which sources were found.', 'Review at several levels: accuracy of facts, strength of evidence, logical flow, connection to the question, referencing and compliance with assessment requirements.', 'Reflection should identify real decisions and learning from the process. Useful reflection explains what changed, why it changed and what effect the change had on the quality or management of the project.', 'Authentication is part of good project management. Keep drafts, notes, source records and supervisor evidence so the development of the work can be demonstrated honestly.'],
      evidence: ['Final review should use the official task requirements and centre guidance as a checklist.', 'References should allow a reader to trace important evidence back to its source.', 'Process records support both reflection and authentication.'],
      analysis: ['Does every section help answer the question?', 'What is the weakest evidence supporting the conclusion?', 'What would a reader need clarified before submission?']
    }
  }
}

export function extraDepthFor(subjectSlug, topicSlug) {
  return EXTRA_DEPTH?.[subjectSlug]?.[topicSlug] || null
}
