import React,{useMemo,useState} from 'react'
import {Building2,CalendarPlus,CheckCircle2,Home,MapPin,Plus,Scale,Star,TrainFront,UtensilsCrossed,WashingMachine,WalletCards} from 'lucide-react'
import {supabase} from './supabase.js'
import './phase3-university.css'

const STARTER_SKILLS=[
  ['Cooking','Plan and cook three simple evening meals'],['Cooking','Prepare a safe packed lunch'],['Laundry','Sort and wash a normal laundry load'],['Laundry','Read clothing care labels'],['Budgeting','Plan a weekly food and travel budget'],['Shopping','Complete a weekly food shop from a list'],['Travel','Plan an unfamiliar public transport journey'],['Appointments','Book and manage an appointment'],['Household','Clean a bathroom and kitchen safely'],['Household','Change bedding and manage a weekly cleaning routine'],['Personal organisation','Keep important documents and deadlines organised'],['Accommodation','Understand halls, deposits and basic tenancy responsibilities']
]
const CURRENT_EXAMPLES=['University of Southampton','Edge Hill University','University of Wolverhampton','Swansea University','University of Exeter']
const arr=v=>v?.split(/\n|,/).map(x=>x.trim()).filter(Boolean)||[]
const fmt=v=>v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v)):''

export default function Phase3University({session,universities=[],skills=[],events=[],loadAll,notify}){
  const [tab,setTab]=useState('research'),[editing,setEditing]=useState(null),[skillEdit,setSkillEdit]=useState(null)
  const [form,setForm]=useState(emptyUniversity())
  const favourites=useMemo(()=>universities.filter(u=>u.favourite||['shortlist','favourite','applied'].includes(u.status)).slice(0,4),[universities])

  function emptyUniversity(){return {name:'',course:'',code:'',campus:'',status:'researching',favourite:false,entry:'',modules:'',assessment:'',placements:'',accommodation:'',travel:'',openDay:'',notes:'',rating:'',questions:''}}
  function editUniversity(u){setEditing(u.id);setForm({name:u.university_name||'',course:u.course_name||'',code:u.course_code||'',campus:u.campus||'',status:u.status||'researching',favourite:!!u.favourite,entry:u.entry_requirements||'',modules:(u.modules||[]).join('\n'),assessment:(u.assessment_methods||[]).join('\n'),placements:u.placements||'',accommodation:u.accommodation_notes||'',travel:u.travel_notes||'',openDay:u.open_day_notes||'',notes:u.notes||'',rating:u.own_rating||'',questions:(u.questions||[]).join('\n')});setTab('research')}
  async function saveUniversity(e){e.preventDefault();const payload={user_id:session.user.id,university_name:form.name.trim(),course_name:form.course.trim()||null,course_code:form.code.trim()||null,campus:form.campus.trim()||null,status:form.status,favourite:form.favourite,entry_requirements:form.entry.trim()||null,modules:arr(form.modules),assessment_methods:arr(form.assessment),placements:form.placements.trim()||null,accommodation_notes:form.accommodation.trim()||null,travel_notes:form.travel.trim()||null,open_day_notes:form.openDay.trim()||null,notes:form.notes.trim()||null,own_rating:form.rating?Number(form.rating):null,questions:arr(form.questions),last_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()};const q=editing?supabase.from('university_choices').update(payload).eq('id',editing):supabase.from('university_choices').insert(payload);const {error}=await q;if(error)return notify?.(error.message);setEditing(null);setForm(emptyUniversity());await loadAll();notify?.('University research saved.')}
  async function addExamples(){for(const name of CURRENT_EXAMPLES){if(universities.some(u=>u.university_name===name))continue;await supabase.from('university_choices').insert({user_id:session.user.id,university_name:name,status:'researching',last_checked_at:new Date().toISOString()})}await loadAll();notify?.('Current university examples added for research. Check all facts on the university website before applying.')}

  async function seedSkills(){const rows=STARTER_SKILLS.map(([category,skill])=>({user_id:session.user.id,category,skill,status:'to_learn',confidence:0,next_action:'Choose one small practice opportunity.'}));const {error}=await supabase.from('independent_skills').upsert(rows,{onConflict:'user_id,category,skill',ignoreDuplicates:true});if(error)return notify?.(error.message);await loadAll();notify?.('University-life starter skills added.')}
  async function updateSkill(skill,patch){const {error}=await supabase.from('independent_skills').update({...patch,updated_at:new Date().toISOString()}).eq('id',skill.id);if(error)return notify?.(error.message);await loadAll();setSkillEdit(null)}
  async function planSkill(skill){const d=new Date();d.setDate(d.getDate()+3);d.setHours(17,30,0,0);const {error}=await supabase.from('planner_events').insert({user_id:session.user.id,title:`Life skill: ${skill.skill}`,category:'personal',starts_at:d.toISOString(),ends_at:new Date(d.getTime()+45*60000).toISOString(),notes:skill.next_action||'Practise this skill once, then record what went well.'});if(error)return notify?.(error.message);notify?.('A practice session was added to Planner for three days from now.')}

  return <div className="p3u-shell">
    <section className="p3u-head"><div><span>University preparation</span><h2>Research the course and prepare for living independently.</h2><p>Changing facts such as entry requirements must be checked against the university's current official information before decisions are made.</p></div><Building2/></section>
    <div className="p3u-tabs"><button className={tab==='research'?'active':''} onClick={()=>setTab('research')}>University research</button><button className={tab==='compare'?'active':''} onClick={()=>setTab('compare')}>Compare choices</button><button className={tab==='life'?'active':''} onClick={()=>setTab('life')}>Independent living</button></div>

    {tab==='research'&&<div className="p3u-grid"><section className="p3u-card"><div className="p3u-card-head"><div><h3>My university research</h3><p>{universities.length} saved</p></div>{!universities.length&&<button onClick={addExamples}><Plus/> Add current examples</button>}</div>{universities.map(u=><article className="p3u-uni" key={u.id}><div className="p3u-icon"><Building2/></div><div><div className="p3u-name"><strong>{u.university_name}</strong>{u.favourite&&<Star/>}</div><span>{u.course_name||'Course to research'}{u.campus?` · ${u.campus}`:''}</span><small>{u.entry_requirements?`Entry: ${u.entry_requirements}`:'Entry requirements not recorded'} · {u.last_checked_at?`checked ${fmt(u.last_checked_at)}`:'not checked'}</small>{u.notes&&<p>{u.notes}</p>}</div><div className="p3u-uni-side">{u.own_rating&&<span className="p3u-rating">{u.own_rating}/5</span>}<button onClick={()=>editUniversity(u)}>Edit research</button></div></article>)}</section>
      <form className="p3u-card p3u-form" onSubmit={saveUniversity}><h3>{editing?'Update university':'Add university research'}</h3><label>University<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="p3u-two"><label>Course<input value={form.course} onChange={e=>setForm({...form,course:e.target.value})}/></label><label>Course code<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label></div><div className="p3u-two"><label>Campus<input value={form.campus} onChange={e=>setForm({...form,campus:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="researching">Researching</option><option value="shortlist">Shortlist</option><option value="favourite">Favourite</option><option value="not_for_me">Not for me</option><option value="applied">Applied</option></select></label></div><label>Current entry requirements<input value={form.entry} onChange={e=>setForm({...form,entry:e.target.value})} placeholder="Record what you verified on the official course page"/></label><label>Modules <span>one per line</span><textarea rows="4" value={form.modules} onChange={e=>setForm({...form,modules:e.target.value})}/></label><label>Assessment methods <span>one per line</span><textarea rows="3" value={form.assessment} onChange={e=>setForm({...form,assessment:e.target.value})}/></label><div className="p3u-two"><label>Placements / opportunities<textarea rows="3" value={form.placements} onChange={e=>setForm({...form,placements:e.target.value})}/></label><label>Accommodation notes<textarea rows="3" value={form.accommodation} onChange={e=>setForm({...form,accommodation:e.target.value})}/></label></div><label>Travel / getting home<textarea rows="2" value={form.travel} onChange={e=>setForm({...form,travel:e.target.value})}/></label><label>Open-day notes<textarea rows="3" value={form.openDay} onChange={e=>setForm({...form,openDay:e.target.value})}/></label><label>Kellyn's own notes/preferences<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="p3u-two"><label>Own rating<select value={form.rating} onChange={e=>setForm({...form,rating:e.target.value})}><option value="">Not rated</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label className="p3u-check"><input type="checkbox" checked={form.favourite} onChange={e=>setForm({...form,favourite:e.target.checked})}/> Favourite</label></div><label>Questions to ask <span>one per line</span><textarea rows="3" value={form.questions} onChange={e=>setForm({...form,questions:e.target.value})}/></label><div className="p3u-actions"><button>{editing?'Save changes':'Add university'}</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setForm(emptyUniversity())}}>Cancel</button>}</div></form></div>}

    {tab==='compare'&&<section className="p3u-compare"><div className="p3u-compare-head"><Scale/><div><h3>Compare the shortlist</h3><p>Use Kellyn's own priorities. A blank cell means more research is needed.</p></div></div>{favourites.length?<div className="p3u-table-wrap"><table><thead><tr><th>Compare</th>{favourites.map(u=><th key={u.id}>{u.university_name}<small>{u.course_name||''}</small></th>)}</tr></thead><tbody><tr><th>Entry requirements</th>{favourites.map(u=><td key={u.id}>{u.entry_requirements||'Research'}</td>)}</tr><tr><th>Modules</th>{favourites.map(u=><td key={u.id}>{u.modules?.slice(0,4).join(', ')||'Research'}</td>)}</tr><tr><th>Assessment</th>{favourites.map(u=><td key={u.id}>{u.assessment_methods?.join(', ')||'Research'}</td>)}</tr><tr><th>Placement / opportunities</th>{favourites.map(u=><td key={u.id}>{u.placements||'Research'}</td>)}</tr><tr><th>Accommodation</th>{favourites.map(u=><td key={u.id}>{u.accommodation_notes||'Research'}</td>)}</tr><tr><th>Travel</th>{favourites.map(u=><td key={u.id}>{u.travel_notes||'Research'}</td>)}</tr><tr><th>Kellyn's rating</th>{favourites.map(u=><td key={u.id}>{u.own_rating?`${u.own_rating}/5`:'Not rated'}</td>)}</tr></tbody></table></div>:<p className="p3u-empty">Mark universities as Shortlist or Favourite to compare them here.</p>}</section>}

    {tab==='life'&&<div className="p3u-life"><section className="p3u-life-head"><div><h3>Independent living preparation</h3><p>Practise real skills gradually before university rather than trying to learn everything at once.</p></div>{!skills.length&&<button onClick={seedSkills}><Plus/> Add starter skills</button>}</section><div className="p3u-skill-grid">{skills.map(skill=><article className="p3u-skill" key={skill.id}><div className="p3u-skill-top"><span className="p3u-skill-icon">{skill.category==='Cooking'?<UtensilsCrossed/>:skill.category==='Laundry'?<WashingMachine/>:skill.category==='Budgeting'?<WalletCards/>:skill.category==='Travel'?<TrainFront/>:<Home/>}</span><div><small>{skill.category}</small><strong>{skill.skill}</strong></div><span className={`p3u-status ${skill.status}`}>{skill.status.replace('_',' ')}</span></div>{skill.next_action&&<p><b>Next:</b> {skill.next_action}</p>}<div className="p3u-confidence"><span>Confidence</span><strong>{skill.confidence||0}/5</strong></div>{skillEdit===skill.id?<div className="p3u-skill-edit"><label>Status<select defaultValue={skill.status} id={`status-${skill.id}`}><option value="to_learn">To learn</option><option value="practising">Practising</option><option value="confident">Confident</option></select></label><label>Confidence<select defaultValue={skill.confidence||0} id={`conf-${skill.id}`}>{[0,1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Next small action<input defaultValue={skill.next_action||''} id={`next-${skill.id}`}/></label><label>Evidence / what happened<textarea rows="2" defaultValue={skill.evidence||''} id={`evidence-${skill.id}`}/></label><button onClick={()=>updateSkill(skill,{status:document.getElementById(`status-${skill.id}`).value,confidence:Number(document.getElementById(`conf-${skill.id}`).value),next_action:document.getElementById(`next-${skill.id}`).value||null,evidence:document.getElementById(`evidence-${skill.id}`).value||null,last_practised_at:new Date().toISOString()})}>Save</button></div>:<div className="p3u-skill-actions"><button onClick={()=>setSkillEdit(skill.id)}>Update</button><button className="secondary" onClick={()=>planSkill(skill)}><CalendarPlus/> Plan practice</button></div>}</article>)}{!skills.length&&<p className="p3u-empty">Add the starter skills, then remove or ignore anything Kellyn already does confidently.</p>}</div></div>}
  </div>
}
