import React,{useEffect,useMemo,useState} from 'react'
import {BarChart3,BookOpen,CalendarPlus,ClipboardList,GraduationCap,ShieldCheck,Target,UserRound,WalletCards} from 'lucide-react'
import {supabase} from './supabase.js'
import './phase3-support.css'

const fmt=v=>v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(new Date(v)):''
const dueSort=(a,b)=>(a.due_at?new Date(a.due_at):Infinity)-(b.due_at?new Date(b.due_at):Infinity)
export default function Phase3Support({profile,subjects=[],notify}){
  const [students,setStudents]=useState([]),[studentId,setStudentId]=useState(''),[data,setData]=useState({tasks:[],learning:[],practice:[],universities:[],skills:[],timetable:[],travel:[],prefs:null}),[loading,setLoading]=useState(false)
  const names=Object.fromEntries(subjects.map(s=>[s.slug,s.short_name]))
  useEffect(()=>{if(profile?.role!=='admin')return;supabase.from('profiles').select('id,display_name,role,created_at').eq('role','student').order('display_name').then(({data,error})=>{if(error)return notify?.(error.message);setStudents(data||[]);if(data?.length&&!studentId)setStudentId(data[0].id)})},[profile?.role])
  useEffect(()=>{if(studentId)loadStudent(studentId)},[studentId])
  async function loadStudent(id){setLoading(true);const qs=await Promise.all([supabase.from('tasks').select('*').eq('user_id',id).order('due_at',{ascending:true,nullsFirst:false}),supabase.from('learning_progress').select('*').eq('user_id',id),supabase.from('practice_records').select('*').eq('user_id',id).order('completed_at',{ascending:false}),supabase.from('university_choices').select('*').eq('user_id',id),supabase.from('independent_skills').select('*').eq('user_id',id),supabase.from('timetable_entries').select('*').eq('user_id',id).order('day_of_week').order('start_time'),supabase.from('travel_entries').select('*').eq('user_id',id).eq('active',true),supabase.from('support_preferences').select('*').eq('user_id',id).maybeSingle()]);const err=qs.find(q=>q.error)?.error;if(err)notify?.(err.message);setData({tasks:qs[0].data||[],learning:qs[1].data||[],practice:qs[2].data||[],universities:qs[3].data||[],skills:qs[4].data||[],timetable:qs[5].data||[],travel:qs[6].data||[],prefs:qs[7].data||null});setLoading(false)}
  async function addTask(e){e.preventDefault();const fd=new FormData(e.currentTarget);const {data:t,error}=await supabase.from('tasks').insert({user_id:studentId,title:fd.get('title'),subject_slug:fd.get('subject')||null,due_at:fd.get('due')?new Date(`${fd.get('due')}T16:00:00`).toISOString():null,status:'not_started',next_action:'Read the task and identify what it is asking.',assessed:fd.get('assessed')==='on'}).select().single();if(error)return notify?.(error.message);await supabase.from('task_steps').insert([{task_id:t.id,user_id:studentId,title:'Read the task and identify the command word.',order_index:0,estimated_minutes:10},{task_id:t.id,user_id:studentId,title:'Gather the notes, sources or teacher guidance needed.',order_index:1,estimated_minutes:10},{task_id:t.id,user_id:studentId,title:'Make a simple plan in your own words.',order_index:2,estimated_minutes:15}]);e.currentTarget.reset();await loadStudent(studentId);notify?.('Task added to the student work queue.')}
  async function addEvent(e){e.preventDefault();const fd=new FormData(e.currentTarget);const start=new Date(fd.get('start'));const {error}=await supabase.from('planner_events').insert({user_id:studentId,title:fd.get('title'),category:fd.get('category'),starts_at:start.toISOString(),ends_at:new Date(start.getTime()+Number(fd.get('minutes')||60)*60000).toISOString(),notes:fd.get('notes')||null});if(error)return notify?.(error.message);e.currentTarget.reset();notify?.('Planner event added.')}
  async function savePrefs(patch){const payload={user_id:studentId,...(data.prefs||{}),...patch};delete payload.id;delete payload.created_at;delete payload.updated_at;const {data:p,error}=await supabase.from('support_preferences').upsert(payload,{onConflict:'user_id'}).select().single();if(error)return notify?.(error.message);setData(d=>({...d,prefs:p}))}

  if(profile?.role!=='admin')return <div className="p3s-locked"><ShieldCheck/><h2>Support view is not enabled for this account.</h2><p>Kellyn's everyday account should remain a student account. Support access is kept separate.</p></div>
  const student=students.find(s=>s.id===studentId),open=[...data.tasks].filter(t=>t.status!=='completed').sort(dueSort),confident=data.learning.filter(x=>x.status==='confident').length,needs=data.learning.filter(x=>x.status==='needs_review').length,activeTargets=data.practice.filter(p=>p.improvement_target&&p.target_status==='active'),skillsConf=data.skills.filter(s=>s.status==='confident').length,aiUses=data.practice.filter(p=>['server_ai','external_ai'].includes(p.marking_mode)).length
  return <div className="p3s-shell"><section className="p3s-head"><div><span>Support view</span><h2>Help organise without turning the Hub into surveillance.</h2><p>This view is for timetable, deadlines, resources and high-level progress. Kellyn's learning remains her own.</p></div><UserRound/></section>
    {!students.length?<section className="p3s-empty"><UserRound/><h3>No student account exists yet.</h3><p>The current account is the Dave/support account. Create Kellyn's own account from the sign-in screen when you are ready. New accounts remain student accounts by default.</p></section>:<><div className="p3s-student"><label>Student<select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.display_name||'Student'}</option>)}</select></label><span>{loading?'Refreshing…':student?.display_name}</span></div>
    <div className="p3s-metrics"><div><ClipboardList/><strong>{open.length}</strong><span>open tasks</span></div><div><BookOpen/><strong>{confident}</strong><span>topics confident</span></div><div><Target/><strong>{needs}</strong><span>need another look</span></div><div><BarChart3/><strong>{activeTargets.length}</strong><span>practice targets</span></div><div><GraduationCap/><strong>{data.universities.length}</strong><span>universities saved</span></div><div><WalletCards/><strong>{skillsConf}/{data.skills.length}</strong><span>life skills confident</span></div></div>
    <div className="p3s-grid"><section className="p3s-card"><h3>Upcoming work</h3>{open.slice(0,8).map(t=><article key={t.id}><div><strong>{t.title}</strong><span>{names[t.subject_slug]||'General'} · {t.due_at?`due ${fmt(t.due_at)}`:'no deadline'}</span></div><small>{t.next_action||'Next action not set'}</small></article>)}{!open.length&&<p className="p3s-muted">No open tasks.</p>}</section><section className="p3s-card"><h3>Learning and practice</h3><div className="p3s-row"><span>Getting there</span><strong>{data.learning.filter(x=>x.status==='developing').length}</strong></div><div className="p3s-row"><span>Need another look</span><strong>{needs}</strong></div><div className="p3s-row"><span>Practice attempts</span><strong>{data.practice.length}</strong></div><div className="p3s-row"><span>Practice AI feedback uses</span><strong>{aiUses}</strong></div>{activeTargets.slice(0,4).map(t=><div className="p3s-target" key={t.id}><Target/><span>{names[t.subject_slug]||'General'}: {t.improvement_target}</span></div>)}</section></div>
    <div className="p3s-grid"><form className="p3s-card p3s-form" onSubmit={addTask}><h3>Add work/deadline</h3><input name="title" required placeholder="Task title"/><select name="subject"><option value="">General</option>{subjects.map(s=><option value={s.slug} key={s.slug}>{s.short_name}</option>)}</select><input type="date" name="due"/><label className="p3s-check"><input type="checkbox" name="assessed"/> Assessed schoolwork</label><button>Add to My Work</button></form><form className="p3s-card p3s-form" onSubmit={addEvent}><h3>Add planner event</h3><input name="title" required placeholder="Event"/><input type="datetime-local" name="start" required/><div className="p3s-two"><select name="category"><option value="school">School</option><option value="revision">Revision</option><option value="activity">Activity</option><option value="ucas">UCAS</option><option value="university">University</option><option value="personal">Personal</option></select><input type="number" name="minutes" defaultValue="60" min="10"/></div><textarea name="notes" rows="2" placeholder="Notes (optional)"/><button><CalendarPlus/> Add event</button></form></div>
    <section className="p3s-card"><h3>What the support view shows</h3><div className="p3s-pref-grid">{[['show_deadlines','Deadlines and work'],['show_learning_progress','Learning progress'],['show_ucas','UCAS/university progress'],['show_independent_living','Independent living progress']].map(([key,label])=><label key={key}><span>{label}</span><input type="checkbox" checked={data.prefs?.[key]??true} onChange={e=>savePrefs({[key]:e.target.checked})}/></label>)}</div><p className="p3s-muted">These controls are designed to support organisation, not to monitor every action Kellyn takes.</p></section></>}
  </div>
}
