import React,{useEffect,useState} from 'react'
import {Accessibility,Bell,BellOff,ShieldCheck} from 'lucide-react'
import {supabase} from './supabase.js'
import './phase2-settings.css'

export default function Phase2Settings({profile,updateProfile,session,skills=[],loadAll,notify}){
  const [prefs,setPrefs]=useState({enabled:false,lesson_minutes_before:10,task_minutes_before:1440,nearly_finished:true,deadline_progress:true});const [permission,setPermission]=useState(typeof Notification==='undefined'?'unsupported':Notification.permission)
  useEffect(()=>{if(!session?.user?.id)return;supabase.from('notification_preferences').select('*').eq('user_id',session.user.id).maybeSingle().then(({data,error})=>{if(error)notify?.(error.message);if(data)setPrefs(data)})},[session?.user?.id])
  async function savePrefs(patch){const next={...prefs,...patch,user_id:session.user.id,updated_at:new Date().toISOString()};const {data,error}=await supabase.from('notification_preferences').upsert(next,{onConflict:'user_id'}).select().single();if(error)return notify?.(error.message);setPrefs(data)}
  async function enableNotifications(){if(!('Notification'in window))return notify?.('This browser does not support notifications.');const result=await Notification.requestPermission();setPermission(result);if(result==='granted'){await savePrefs({enabled:true});notify?.('Action notifications enabled while Kellyn Hub is open or installed and active.')}else notify?.('Notification permission was not granted.')}
  async function addSkill(e){e.preventDefault();const fd=new FormData(e.currentTarget);const {error}=await supabase.from('independent_skills').upsert({user_id:session.user.id,category:fd.get('category'),skill:fd.get('skill'),status:'to_learn'},{onConflict:'user_id,category,skill'});if(error)return notify?.(error.message);e.currentTarget.reset();await loadAll()}
  async function cycleSkill(skill){const next=skill.status==='to_learn'?'practising':skill.status==='practising'?'confident':'to_learn';const {error}=await supabase.from('independent_skills').update({status:next,updated_at:new Date().toISOString()}).eq('id',skill.id);if(error)return notify?.(error.message);await loadAll()}
  return <div className="p2s-shell">
    <section className="p2s-card"><div className="p2s-title"><Accessibility/><div><strong>Accessibility</strong><span>Part of the base design, not an extra mode</span></div></div><label className="p2s-row"><span><strong>OpenDyslexic</strong><small>Default dyslexia-friendly font. Turn off only if Kellyn prefers the alternative.</small></span><input type="checkbox" checked={profile?.dyslexic_font!==false} onChange={e=>updateProfile({dyslexic_font:e.target.checked})}/></label><label className="p2s-row"><span><strong>Dark mode</strong><small>Use the darker colour scheme.</small></span><input type="checkbox" checked={!!profile?.dark_mode} onChange={e=>updateProfile({dark_mode:e.target.checked})}/></label><label className="p2s-row"><span><strong>Reduced motion</strong><small>Reduce non-essential animation.</small></span><input type="checkbox" checked={!!profile?.reduced_motion} onChange={e=>updateProfile({reduced_motion:e.target.checked})}/></label><label className="p2s-range"><span><strong>Text size</strong><small>{Math.round((profile?.text_scale||1)*100)}%</small></span><input type="range" min="0.9" max="1.4" step="0.1" value={profile?.text_scale||1} onChange={e=>updateProfile({text_scale:Number(e.target.value)})}/></label></section>
    <section className="p2s-card"><div className="p2s-title"><Bell/><div><strong>Action notifications</strong><span>Selective prompts, not constant reminders</span></div></div>{permission==='unsupported'?<div className="p2s-note"><BellOff/>Notifications are not supported by this browser.</div>:permission!=='granted'?<button className="p2s-enable" onClick={enableNotifications}><Bell/> Allow notifications</button>:<><label className="p2s-row"><span><strong>Notifications enabled</strong><small>Switch off without removing browser permission.</small></span><input type="checkbox" checked={!!prefs.enabled} onChange={e=>savePrefs({enabled:e.target.checked})}/></label><label className="p2s-range"><span><strong>Lesson transition</strong><small>{prefs.lesson_minutes_before} minutes before</small></span><input type="range" min="5" max="30" step="5" value={prefs.lesson_minutes_before} onChange={e=>savePrefs({lesson_minutes_before:Number(e.target.value)})}/></label><label className="p2s-row"><span><strong>Nearly finished prompts</strong><small>Surface a task when only a small amount remains.</small></span><input type="checkbox" checked={!!prefs.nearly_finished} onChange={e=>savePrefs({nearly_finished:e.target.checked})}/></label><label className="p2s-row"><span><strong>Deadline progress prompts</strong><small>Include the best next action rather than a generic warning.</small></span><input type="checkbox" checked={!!prefs.deadline_progress} onChange={e=>savePrefs({deadline_progress:e.target.checked})}/></label></>}<div className="p2s-note"><ShieldCheck/><span>These browser notifications work while the Hub/PWA is active. True background push when the app is fully closed needs a later push service and is not being presented as complete yet.</span></div></section>
    <section className="p2s-card p2s-skills"><div className="p2s-title"><ShieldCheck/><div><strong>Independent living skills</strong><span>Secondary preparation for university life</span></div></div><form onSubmit={addSkill}><input name="category" placeholder="Category, e.g. Cooking" required/><input name="skill" placeholder="Skill" required/><button>Add skill</button></form>{skills.map(s=><button className="p2s-skill" key={s.id} onClick={()=>cycleSkill(s)}><span><strong>{s.skill}</strong><small>{s.category}</small></span><em>{s.status.replace('_',' ')}</em></button>)}{!skills.length&&<p className="p2s-empty">No independent-living skills tracked yet.</p>}</section>
  </div>
}
