import React,{useMemo,useState} from 'react'
import {Brain,CheckCircle2,Clipboard,Copy,Sparkles,Target,Timer,ShieldCheck,AlertTriangle} from 'lucide-react'
import {supabase} from './supabase.js'
import './phase3-practice.css'

const TYPES=[['knowledge_check','Knowledge check'],['essay','Essay practice'],['source_question','Source question'],['mock','Full mock'],['recall','Recall'],['other','Other practice']]
const fmt=v=>v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v)):''
const pct=r=>r?.score!=null&&r?.score_out_of?Math.round(Number(r.score)/Number(r.score_out_of)*100):null

function markingPrompt(record,subject){
  return `This is PRACTICE ONLY and is not being submitted to school.\n\nSubject: WJEC ${subject||record.subject_slug||'subject'}\nPractice type: ${record.practice_type}\nQuestion:\n${record.question||record.title}\n\nLearner response:\n${record.response||'(response not supplied)'}\n\nMark scheme / assessment guidance supplied:\n${record.mark_scheme||'No specific mark scheme supplied. Give skills-based feedback only and do not invent an official mark scheme.'}\n\nMaximum mark: ${record.score_out_of||'not supplied'}\n\nPlease act as a practice assessor only. Do not rewrite the answer and do not provide a submission-ready model response. Where a mark scheme is supplied, apply it carefully. Return: 1) practice score only if justified, 2) two things done well, 3) no more than two areas to improve, 4) one specific improvement target for the next practice, 5) one short practice activity that would help with that target. Make clear that this is practice feedback, not a teacher grade prediction.`
}

export default function Phase3Practice({session,subjects=[],practice=[],loadAll,notify}){
  const [tab,setTab]=useState('cycle'),[busy,setBusy]=useState(''),[selected,setSelected]=useState(null)
  const [form,setForm]=useState({subject:'',type:'knowledge_check',title:'',question:'',response:'',markScheme:'',max:''})
  const subjectNames=Object.fromEntries(subjects.map(s=>[s.slug,s.short_name]))
  const records=useMemo(()=>[...practice].sort((a,b)=>new Date(b.completed_at)-new Date(a.completed_at)),[practice])
  const activeTargets=records.filter(r=>r.improvement_target&&r.target_status==='active')

  async function savePractice(e){
    e.preventDefault();setBusy('save')
    const payload={user_id:session.user.id,subject_slug:form.subject||null,title:form.title.trim(),practice_type:form.type,question:form.question.trim()||null,response:form.response.trim()||null,mark_scheme:form.markScheme.trim()||null,score_out_of:form.max?Number(form.max):null,marking_mode:'self',reflection:'Practice response saved for review.',completed_at:new Date().toISOString()}
    const {data,error}=await supabase.from('practice_records').insert(payload).select().single();setBusy('')
    if(error)return notify?.(error.message)
    setSelected(data);setForm({subject:form.subject,type:form.type,title:'',question:'',response:'',markScheme:'',max:''});await loadAll();setTab('review');notify?.('Practice saved. Review it before asking for feedback.')
  }

  async function runAi(record){
    if(!record?.response)return notify?.('Add a practice response before requesting feedback.')
    setBusy(record.id)
    const {data,error}=await supabase.functions.invoke('mock-marker',{body:{practice_only:true,assessed:false,subject:subjectNames[record.subject_slug]||record.subject_slug,question:record.question||record.title,response:record.response,mark_scheme:record.mark_scheme,max_mark:record.score_out_of,practice_type:record.practice_type}})
    if(error||!data?.configured){setBusy('');await navigator.clipboard?.writeText(markingPrompt(record,subjectNames[record.subject_slug]));return notify?.('Server AI marking is not configured yet. A safe practice-marking prompt has been copied instead.')}
    const f=data.feedback||{}
    const patch={score:f.score??record.score,score_out_of:f.score_out_of??record.score_out_of,feedback_good:Array.isArray(f.what_went_well)?f.what_went_well.slice(0,2):[],feedback_improve:Array.isArray(f.improve)?f.improve.slice(0,2):[],improvement_target:f.target||null,ai_feedback:f,marking_mode:'server_ai',target_status:'active'}
    const {error:updateError}=await supabase.from('practice_records').update(patch).eq('id',record.id);setBusy('')
    if(updateError)return notify?.(updateError.message);await loadAll();setSelected({...record,...patch});notify?.('Practice feedback saved.')
  }

  async function copyPrompt(record){await navigator.clipboard?.writeText(markingPrompt(record,subjectNames[record.subject_slug]));notify?.('Safe practice-marking prompt copied.')}
  async function targetStatus(record,status){const {error}=await supabase.from('practice_records').update({target_status:status}).eq('id',record.id);if(error)return notify?.(error.message);await loadAll();notify?.(status==='improved'?'Target marked as improved.':'Target updated.')}

  const current=selected||records[0]
  return <div className="p3-practice">
    <section className="p3-practice-head"><div><span>Practice Mode</span><h2>Mock → Feedback → Target → Practise → Next Mock</h2><p>This area is deliberately separate from genuine school assignments. Practice can be marked and reviewed here.</p></div><ShieldCheck/></section>
    <div className="p3-tabs"><button className={tab==='cycle'?'active':''} onClick={()=>setTab('cycle')}>Practice cycle</button><button className={tab==='new'?'active':''} onClick={()=>setTab('new')}>New practice</button><button className={tab==='review'?'active':''} onClick={()=>setTab('review')}>Review feedback</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>History</button></div>

    {tab==='cycle'&&<div className="p3-cycle-grid"><section className="p3-card"><div className="p3-title"><Target/><div><strong>Current improvement targets</strong><span>Keep the next practice focused.</span></div></div>{activeTargets.slice(0,5).map(r=><article className="p3-target" key={r.id}><div><strong>{subjectNames[r.subject_slug]||'General'}</strong><p>{r.improvement_target}</p><small>From {r.title} · {fmt(r.completed_at)}</small></div><button onClick={()=>targetStatus(r,'improved')}>Target improved</button></article>)}{!activeTargets.length&&<p className="p3-empty">No active target yet. Complete or review a practice first.</p>}</section><section className="p3-card"><div className="p3-title"><Brain/><div><strong>Choose the next practice</strong><span>One useful activity, not a long list.</span></div></div>{activeTargets[0]?<><p>Next, practise the target from <strong>{activeTargets[0].title}</strong>.</p><div className="p3-next"><Timer/><span>Use a short 15–25 minute question focused on:</span><strong>{activeTargets[0].improvement_target}</strong></div><button onClick={()=>{setForm(f=>({...f,subject:activeTargets[0].subject_slug||'',title:`Target practice: ${activeTargets[0].title}`}));setTab('new')}}>Start target practice</button></>:<><p>Start with a short knowledge check or one exam-style question.</p><button onClick={()=>setTab('new')}>Start practice</button></>}</section></div>}

    {tab==='new'&&<form className="p3-practice-form" onSubmit={savePractice}><div className="p3-form-head"><Brain/><div><h3>Create a practice attempt</h3><p>Use your own practice question, a teacher-approved practice question or a question from an official resource.</p></div></div><div className="p3-two"><label>Subject<select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}><option value="">General</option>{subjects.map(s=><option key={s.slug} value={s.slug}>{s.short_name}</option>)}</select></label><label>Practice type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label>Practice title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Crime and Deviance 20-mark practice"/></label><label>Question<textarea rows="3" value={form.question} onChange={e=>setForm({...form,question:e.target.value})} placeholder="Paste or type the practice question."/></label><label>Kellyn's practice response<textarea rows="10" value={form.response} onChange={e=>setForm({...form,response:e.target.value})} placeholder="Paste the response Kellyn wrote herself."/></label><div className="p3-two"><label>Maximum mark<input type="number" min="1" value={form.max} onChange={e=>setForm({...form,max:e.target.value})}/></label><label>Mark scheme or assessment guidance <span>optional</span><textarea rows="4" value={form.markScheme} onChange={e=>setForm({...form,markScheme:e.target.value})} placeholder="Paste only the relevant guidance if available."/></label></div><div className="p3-boundary"><AlertTriangle/><span>Do not paste genuine assessed schoolwork here for AI marking. This engine is for practice and mock work only.</span></div><button disabled={busy==='save'}>{busy==='save'?'Saving…':'Save practice'}</button></form>}

    {tab==='review'&&<section className="p3-review">{current?<><div className="p3-review-head"><div><span>{subjectNames[current.subject_slug]||'General'} · {TYPES.find(x=>x[0]===current.practice_type)?.[1]||current.practice_type}</span><h3>{current.title}</h3><small>{fmt(current.completed_at)}</small></div>{pct(current)!=null&&<div className="p3-score"><strong>{current.score}/{current.score_out_of}</strong><span>{pct(current)}%</span></div>}</div><div className="p3-review-grid"><div className="p3-card"><strong>Practice question</strong><p>{current.question||current.title}</p><strong>Response</strong><div className="p3-response">{current.response||'No response stored.'}</div></div><div className="p3-card"><strong>Practice feedback</strong>{current.feedback_good?.length?<><h4>What went well</h4>{current.feedback_good.map((x,i)=><div className="p3-feedback good" key={i}><CheckCircle2/>{x}</div>)}</>:<p className="p3-empty">No feedback stored yet.</p>}{current.feedback_improve?.length?<><h4>Areas to improve</h4>{current.feedback_improve.map((x,i)=><div className="p3-feedback improve" key={i}><Target/>{x}</div>)}</>:null}{current.improvement_target&&<div className="p3-target-box"><strong>Next target</strong><p>{current.improvement_target}</p></div>}<div className="p3-review-actions"><button disabled={busy===current.id} onClick={()=>runAi(current)}><Sparkles/> {busy===current.id?'Checking…':'AI practice feedback'}</button><button className="secondary" onClick={()=>copyPrompt(current)}><Copy/> Copy marking prompt</button></div><small className="p3-note">AI feedback is practice support, not a predicted teacher grade. Where no mark scheme is supplied, feedback should be treated as skills-based.</small></div></div></>:<p className="p3-empty">Save a practice attempt first.</p>}</section>}

    {tab==='history'&&<section className="p3-history"><h3>Practice history</h3>{records.map(r=><button key={r.id} onClick={()=>{setSelected(r);setTab('review')}}><span><strong>{r.title}</strong><small>{subjectNames[r.subject_slug]||'General'} · {fmt(r.completed_at)}</small></span><span>{r.score!=null?`${r.score}${r.score_out_of?`/${r.score_out_of}`:''}`:'Review'}</span></button>)}{!records.length&&<p className="p3-empty">No practice recorded yet.</p>}</section>}
  </div>
}
