import React,{useEffect,useMemo,useState} from 'react'
import {BookOpen,CalendarPlus,CheckCircle2,Clock,Download,RotateCcw,Target,TrendingUp} from 'lucide-react'
import {supabase} from './supabase.js'
import {LEARNING_CONTENT,LEARNING_STATUS} from './learningContent.js'
import './phase3-progress.css'

function weekForDate(value){const anchor=new Date(2026,7,31);anchor.setHours(0,0,0,0);const d=new Date(value);d.setHours(0,0,0,0);const w=Math.floor((d-anchor)/604800000);return (((w%2)+2)%2)+1}
function dayIndex(date){return ((date.getDay()+6)%7)+1}
function fmt(value){return new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function flatten(){const out=[];for(const [subjectSlug,c] of Object.entries(LEARNING_CONTENT))for(const unit of c.units||[])for(const topic of unit.topics||[])out.push({subjectSlug,unitSlug:unit.slug,unitTitle:unit.title,topicSlug:topic.slug,title:topic.title,time:topic.time||25});return out}
function freeSlots(timetable=[],events=[]){const slots=[],now=new Date();for(let off=0;off<14&&slots.length<8;off++){const d=new Date(now);d.setDate(now.getDate()+off);const day=dayIndex(d);if(day>5)continue;const week=weekForDate(d);for(const row of timetable.filter(x=>x.day_of_week===day&&(x.week_number||1)===week&&x.entry_type==='free')){const [h,m]=row.start_time.split(':').map(Number),[eh,em]=row.end_time.split(':').map(Number);const start=new Date(d),end=new Date(d);start.setHours(h,m,0,0);end.setHours(eh,em,0,0);if(start<=now)continue;const clash=events.some(e=>new Date(e.starts_at)<end&&new Date(e.ends_at||e.starts_at)>start);if(!clash)slots.push({start,end,label:`${fmt(start)} · free period`})}}return slots}
function scoreTopic(topic,status,progress,practice){let score={needs_review:100,developing:75,not_started:55,confident:20}[status]??50;const reasons=[];if(status==='needs_review')reasons.push('Marked as needing another look');if(status==='developing')reasons.push('Understanding is developing');if(status==='not_started')reasons.push('Not started in the Hub');if(progress?.next_review_at&&new Date(progress.next_review_at)<=new Date()){score+=18;reasons.push('Spaced review is due')}const related=practice.filter(p=>p.subject_slug===topic.subjectSlug&&(p.topic_slug? p.topic_slug===topic.topicSlug:true));const active=related.find(p=>p.improvement_target&&p.target_status==='active');if(active){score+=24;reasons.push(`Active practice target: ${active.improvement_target}`)}const recent=related.sort((a,b)=>new Date(b.completed_at)-new Date(a.completed_at))[0];if(recent?.score!=null&&recent?.score_out_of&&Number(recent.score)/Number(recent.score_out_of)<.6){score+=15;reasons.push('Recent practice was below 60%')}if(recent?.completed_at&&Date.now()-new Date(recent.completed_at).getTime()>21*86400000){score+=8;reasons.push('No recent practice recorded')}return {score,reasons,active,recent}}
function esc(s=''){return String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function icsDate(v){return new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')}
function downloadIcs(events){const rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Kellyn Hub//Planner//EN','CALSCALE:GREGORIAN'];for(const e of events){rows.push('BEGIN:VEVENT',`UID:${e.id||crypto.randomUUID()}@kellynhub`,`DTSTAMP:${icsDate(new Date())}`,`DTSTART:${icsDate(e.starts_at)}`,`DTEND:${icsDate(e.ends_at||new Date(new Date(e.starts_at).getTime()+30*60000))}`,`SUMMARY:${esc(e.title)}`,e.location?`LOCATION:${esc(e.location)}`:'',e.notes?`DESCRIPTION:${esc(e.notes)}`:'','END:VEVENT')}rows.push('END:VCALENDAR');const blob=new Blob([rows.filter(Boolean).join('\r\n')],{type:'text/calendar'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kellyn-hub-planner.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export default function Phase3Progress({session,subjects=[],tasks=[],practice=[],skills=[],timetable=[],events=[],notify,go}){
  const [learning,setLearning]=useState([]),[recs,setRecs]=useState([]),[busy,setBusy]=useState('')
  useEffect(()=>{if(!session?.user?.id)return;Promise.all([supabase.from('learning_progress').select('*').eq('user_id',session.user.id),supabase.from('revision_recommendations').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false})]).then(([a,b])=>{if(a.error)notify?.(a.error.message);else setLearning(a.data||[]);if(b.error)notify?.(b.error.message);else setRecs(b.data||[])})},[session?.user?.id])
  const names=Object.fromEntries(subjects.map(s=>[s.slug,s.short_name]));const topics=useMemo(()=>flatten(),[]);const map=useMemo(()=>new Map(learning.map(r=>[`${r.subject_slug}:${r.unit_slug}:${r.topic_slug}`,r])),[learning]);const slots=useMemo(()=>freeSlots(timetable,events),[timetable,events])
  const queue=useMemo(()=>topics.map(t=>{const p=map.get(`${t.subjectSlug}:${t.unitSlug}:${t.topicSlug}`);const status=p?.status||'not_started';return {...t,status,progress:p,...scoreTopic(t,status,p,practice)}}).sort((a,b)=>b.score-a.score).slice(0,8),[topics,map,practice])
  const weekAgo=Date.now()-7*86400000,finished=tasks.filter(t=>t.status==='completed'&&new Date(t.updated_at||t.created_at).getTime()>=weekAgo),targets=practice.filter(p=>p.improvement_target&&p.target_status==='active').slice(0,5)

  async function plan(topic,slot){setBusy(topic.topicSlug);const start=slot?.start||new Date(Date.now()+86400000);if(!slot)start.setHours(18,0,0,0);const mins=Math.max(20,Math.min(45,topic.time||25)),end=new Date(start.getTime()+mins*60000),target=topic.active?.improvement_target;const notes=`Revision route: 1) Retrieve key knowledge without notes. 2) Check A-level detail/evidence. 3) Complete one application or evaluation activity.${target?` Practice target: ${target}`:''}`;const {error:e1}=await supabase.from('planner_events').insert({user_id:session.user.id,title:`${names[topic.subjectSlug]||topic.subjectSlug}: ${topic.title}`,category:'revision',subject_slug:topic.subjectSlug,starts_at:start.toISOString(),ends_at:end.toISOString(),notes});if(e1){setBusy('');return notify?.(e1.message)}const {data,error}=await supabase.from('revision_recommendations').insert({user_id:session.user.id,subject_slug:topic.subjectSlug,unit_slug:topic.unitSlug,topic_slug:topic.topicSlug,title:`${names[topic.subjectSlug]||topic.subjectSlug}: ${topic.title}`,reason:topic.reasons.join(' · '),estimated_minutes:mins,status:'planned',planned_for:start.toISOString()}).select().single();setBusy('');if(error)return notify?.(error.message);setRecs(cur=>[data,...cur]);notify?.(`Revision planned for ${fmt(start)}.`)}
  async function reviewed(topic){const p=topic.progress;if(!p)return notify?.('Open the topic in Subjects first so progress can be saved.');const days=topic.status==='needs_review'?2:topic.status==='developing'?5:topic.status==='confident'?14:3;const next=new Date();next.setDate(next.getDate()+days);const {error}=await supabase.from('learning_progress').update({last_reviewed_at:new Date().toISOString(),next_review_at:next.toISOString(),review_count:(p.review_count||0)+1}).eq('id',p.id);if(error)return notify?.(error.message);setLearning(cur=>cur.map(x=>x.id===p.id?{...x,last_reviewed_at:new Date().toISOString(),next_review_at:next.toISOString(),review_count:(x.review_count||0)+1}:x));notify?.(`Next spaced review suggested in ${days} days.`)}

  return <div className="p3p-shell"><section className="p3p-head"><div><span>Advanced revision planning</span><h2>Use confidence, practice targets and spaced review together.</h2><p>The queue changes as Kellyn learns, practises and marks topics as more secure.</p></div><button onClick={()=>downloadIcs(events)}><Download/> Export Planner (.ics)</button></section>
    <div className="p3p-summary"><div><strong>{learning.filter(r=>r.status==='confident').length}</strong><span>topics confident</span></div><div><strong>{targets.length}</strong><span>active practice targets</span></div><div><strong>{finished.length}</strong><span>finished this week</span></div><div><strong>{recs.filter(r=>r.status==='planned').length}</strong><span>revision sessions planned</span></div></div>
    <div className="p3p-grid"><section className="p3p-card"><div className="p3p-title"><TrendingUp/><div><strong>Recommended revision queue</strong><span>Highest-value topic first</span></div></div>{queue.map((t,i)=><article className="p3p-topic" key={`${t.unitSlug}:${t.topicSlug}`}><div className="p3p-rank">{i+1}</div><div className="p3p-topic-main"><strong>{names[t.subjectSlug]} · {t.title}</strong><span>{LEARNING_STATUS[t.status]||t.status}</span><p>{t.reasons.length?t.reasons.join(' · '):'Routine spaced learning review'}</p>{t.active&&<div className="p3p-target"><Target/>{t.active.improvement_target}</div>}<small><Clock/> {Math.max(20,Math.min(45,t.time||25))} minutes</small></div><div className="p3p-actions"><select id={`p3slot-${i}`} defaultValue="0">{slots.length?slots.map((s,n)=><option key={s.start.toISOString()} value={n}>{s.label}</option>):<option value="evening">Tomorrow 18:00</option>}</select><button disabled={busy===t.topicSlug} onClick={()=>{const v=document.getElementById(`p3slot-${i}`)?.value;plan(t,v==='evening'?null:slots[Number(v||0)])}}><CalendarPlus/> Plan</button><button className="secondary" onClick={()=>reviewed(t)}><RotateCcw/> Reviewed</button></div></article>)}</section>
      <aside className="p3p-side"><section className="p3p-card"><div className="p3p-title"><Target/><div><strong>Practice targets</strong><span>Carry these into the next attempt</span></div></div>{targets.map(t=><div className="p3p-simple" key={t.id}><span><strong>{names[t.subject_slug]||'General'}</strong>{t.improvement_target}</span><button onClick={()=>go?.('practice')}>Practise</button></div>)}{!targets.length&&<p className="p3p-empty">No active target yet.</p>}</section><section className="p3p-card"><div className="p3p-title"><CheckCircle2/><div><strong>Finished this week</strong><span>Completed work stays visible</span></div></div>{finished.slice(0,7).map(t=><div className="p3p-finished" key={t.id}><CheckCircle2/><span>{t.title}<small>{names[t.subject_slug]||'General'}</small></span></div>)}{!finished.length&&<p className="p3p-empty">Completed work will appear here.</p>}</section><section className="p3p-card"><div className="p3p-title"><BookOpen/><div><strong>Independent living</strong><span>{skills.filter(s=>s.status==='confident').length} confident of {skills.length} tracked</span></div></div><button className="wide" onClick={()=>go?.('uni')}>Open university preparation</button></section></aside></div>
  </div>
}
