const EXAMPLES = {
  sociology: {
    'crime-social-construction': [
      {title:'Mods and Rockers, 1964',example:'Stanley Cohen studied media and public reactions to clashes involving Mods and Rockers at English seaside resorts in 1964. His later analysis in Folk Devils and Moral Panics showed how reporting, prediction and social reaction could magnify a perceived threat.',demonstrates:'The social reaction to behaviour can become part of the sociological explanation. Media attention can help construct folk devils and intensify concern rather than merely record an event.'},
      {title:'Sexual Offences Act 1967',example:'The Sexual Offences Act 1967 partially decriminalised private consensual homosexual acts between men aged over 21 in England and Wales. Later legal changes altered these rules further.',demonstrates:'Legal and social definitions are not fixed. Conduct can move between criminal, tolerated and accepted categories as law, norms and power relationships change.'},
      {title:'Labelling and criminal justice',example:'Howard Becker argued that deviance depends partly on the rules social groups create and the labels applied to rule-breakers. Edwin Lemert distinguished primary deviance from secondary deviance, where social reaction can become part of a person’s later identity and behaviour.',demonstrates:'Interactionism shifts attention from the act alone to selective rule enforcement, identity and the consequences of being publicly defined as deviant.'}
    ],
    'crime-patterns-measurement': [
      {title:'Crime Survey for England and Wales',example:'The Crime Survey for England and Wales asks people about experiences of crime whether or not those incidents were reported to police. It therefore measures something different from police-recorded crime.',demonstrates:'No single data source is a complete count of crime. Victim surveys can reveal part of the hidden figure while bringing their own sampling and recall limitations.'},
      {title:'Cicourel and juvenile justice',example:'Aaron Cicourel’s 1968 study The Social Organization of Juvenile Justice examined how professionals used assumptions and typifications when processing young people through the justice system.',demonstrates:'Official crime patterns can be shaped by institutional decisions about who appears suspicious, who is stopped and who progresses through formal systems.'},
      {title:'Changes in recorded crime',example:'Police-recorded figures can rise after changes in reporting, recording standards, targeted enforcement or public willingness to disclose offences, even when underlying offending has not changed by the same amount.',demonstrates:'Recorded statistics are produced through a social process. A numerical change must be interpreted before it is treated as evidence of a behavioural change.'}
    ],
    'crime-theories': [
      {title:'Merton’s strain theory',example:'Robert Merton argued that societies can promote culturally valued goals while access to legitimate means remains unequal. His “innovation” adaptation describes accepting the goal while using illegitimate means to pursue it.',demonstrates:'Structural pressure can be used to explain some offending without reducing crime to individual moral failure.'},
      {title:'Carlen’s research with women',example:'Pat Carlen’s Women, Crime and Poverty (1988) drew on interviews with women who had been convicted of offences and developed the idea of class and gender deals.',demonstrates:'Feminist criminology can connect offending to gendered expectations, material disadvantage and the circumstances in which conformity may appear less rewarding.'},
      {title:'Lea and Young’s left realism',example:'John Lea and Jock Young developed left realism around relative deprivation, marginalisation and subculture, while also taking victims’ experiences seriously.',demonstrates:'A theory can combine structural causes with practical concern about real victimisation, leading to different policy implications from right realism.'}
    ],
    'crime-policy-evaluation': [
      {title:'Situational crime prevention',example:'Measures such as improved lighting, controlled access, vehicle immobilisers and better guardianship aim to make offending harder or riskier rather than change offenders’ underlying motivations.',demonstrates:'Policy usually contains an assumed cause of crime. Situational prevention treats opportunity as important, which creates both practical strengths and questions about displacement.'},
      {title:'Diversion from formal justice',example:'Youth justice systems can use diversionary responses for some lower-level offending instead of immediately escalating formal criminal processing.',demonstrates:'A labelling perspective predicts that avoiding unnecessary formal labels may reduce some of the negative consequences of criminalisation.'},
      {title:'Crime and Disorder Act 1998',example:'The Crime and Disorder Act 1998 created a statutory framework that included Anti-social Behaviour Orders and wider local crime-and-disorder responsibilities.',demonstrates:'Crime-control policy can reflect assumptions about deterrence, community protection and visible disorder. Evaluation should consider effectiveness, fairness and unintended consequences.'}
    ],
    'methods-design': [
      {title:'Crime Survey research design',example:'The Crime Survey for England and Wales uses a large structured survey to produce comparable victimisation data across repeated waves.',demonstrates:'A standardised design supports comparison and trend analysis, but the method still depends on sampling, memory, disclosure and the scope of questions asked.'},
      {title:'Ann Oakley’s interview research',example:'Ann Oakley’s research on women and motherhood challenged the idea that interviews must always remain detached and impersonal, highlighting the relationship between researcher and participant.',demonstrates:'Methodological choices affect validity and the kind of knowledge produced. Interpretivist research may value rapport and depth even when this reduces strict standardisation.'},
      {title:'Gatekeepers in school research',example:'A researcher studying sixth-form students normally needs access from a school or college. A gatekeeper may restrict which classes, year groups or times are available.',demonstrates:'Practical access can alter the sample and therefore affect representativeness, validity and what conclusions the study can support.'}
    ],
    'inequality-patterns': [
      {title:'ONS Wealth and Assets Survey',example:'The Office for National Statistics Wealth and Assets Survey measures household wealth, including property, pensions, financial wealth and physical assets.',demonstrates:'Wealth is not the same as income. Accumulated assets can reveal inequalities that an annual-income measure alone may hide.'},
      {title:'Gender pay-gap statistics',example:'The Office for National Statistics publishes UK gender pay-gap measures using earnings data. The gap varies by age, occupation, working pattern and other factors.',demonstrates:'A statistical pattern establishes that a difference exists but does not by itself prove one cause. Sociology must explain the mechanisms behind the pattern.'},
      {title:'Welsh Government inequality data',example:'Welsh Government and StatsWales publish evidence on poverty, education, health, housing and labour-market outcomes in Wales.',demonstrates:'National and regional context matters. UK-wide averages can hide patterns that are important when studying inequality in Wales.'}
    ],
    'inequality-theories': [
      {title:'Davis and Moore',example:'Kingsley Davis and Wilbert Moore argued that unequal rewards can help society fill positions requiring scarce skills or lengthy training.',demonstrates:'Functionalism treats some inequality as potentially useful to social organisation, which can be evaluated by asking who defines importance and whether rewards really follow merit.'},
      {title:'Weber’s class, status and party',example:'Max Weber distinguished economic market position from social honour and organised political power.',demonstrates:'Inequality is multidimensional. People can have different combinations of economic resources, prestige and political influence.'},
      {title:'Occupational segregation',example:'Labour-market data repeatedly show that men and women are unevenly distributed across occupations and seniority levels.',demonstrates:'Feminist explanations can examine both horizontal segregation between types of work and vertical segregation in access to senior positions, rather than treating pay as an isolated outcome.'}
    ]
  },
  law: {
    'criminal-liability': [
      {title:'R v White [1910]',example:'The defendant put poison in his mother’s drink intending to kill her, but medical evidence showed she died of an unrelated heart attack before the poison could cause death.',demonstrates:'The “but for” test of factual causation matters even where the defendant has clear criminal intent. Intention alone cannot prove a result crime.'},
      {title:'R v Blaue [1975]',example:'A stabbing victim refused a blood transfusion because of her religious beliefs and died. The defendant remained liable.',demonstrates:'The thin-skull principle means a defendant takes the victim as found. A victim’s characteristics or beliefs do not automatically break legal causation.'},
      {title:'R v Woollin [1999]',example:'The House of Lords considered when a jury may find intention where a prohibited result was not the defendant’s direct purpose, focusing on virtual certainty and the defendant’s appreciation of it.',demonstrates:'Oblique intention is narrower than simply foreseeing a risk. The degree of foresight matters when distinguishing intention from recklessness.'},
      {title:'R v G [2003]',example:'The House of Lords rejected an objective approach to recklessness for criminal damage and focused on whether the defendant actually foresaw the risk.',demonstrates:'Fault in criminal law can depend on the defendant’s own awareness rather than only what a reasonable person would have noticed.'}
    ],
    'criminal-offences-defences': [
      {title:'Offences Against the Person Act 1861',example:'Sections 47, 20 and 18 remain central statutory provisions for non-fatal offences against the person, despite their nineteenth-century wording.',demonstrates:'Similar injuries can fall under different offences because the legal elements and mens rea differ. Accurate application requires more than judging seriousness by appearance.'},
      {title:'Theft Act 1968',example:'Theft, robbery and burglary are defined through separate statutory elements in the Theft Act 1968.',demonstrates:'Property offences overlap but are not interchangeable. A legal answer must identify and prove the elements of the correct offence.'},
      {title:'Criminal Attempts Act 1981',example:'The Act makes a person guilty of attempt where, with intent to commit an offence, they do an act that is more than merely preparatory.',demonstrates:'Criminal liability can arise before a completed offence, but the law sets a threshold so mere preparation is not automatically criminalised as an attempt.'}
    ],
    'contract-formation': [
      {title:'Carlill v Carbolic Smoke Ball Co [1893]',example:'An advertisement promised £100 to users who followed stated instructions and still caught influenza. The court treated it as a unilateral offer capable of acceptance by performance.',demonstrates:'An advertisement is not always merely an invitation to treat. Its wording, certainty and intention can make it an offer.'},
      {title:'Pharmaceutical Society v Boots [1953]',example:'In a self-service shop, the display of goods was treated as an invitation to treat, with the customer making the offer at the checkout.',demonstrates:'Identifying exactly when offer and acceptance occur determines whether and when a contract is formed.'},
      {title:'Entores v Miles Far East [1955]',example:'The case considered acceptance by instantaneous communication and established that acceptance generally takes effect when received.',demonstrates:'Rules of communication affect the time and place of formation. Contract analysis therefore needs the specific method of acceptance.'}
    ],
    'contract-problems-remedies': [
      {title:'Derry v Peek [1889]',example:'The House of Lords set a demanding test for fraudulent misrepresentation, requiring knowledge of falsity, absence of honest belief, or recklessness as to truth.',demonstrates:'Misrepresentation law distinguishes different kinds of false statement and fault. The classification affects the legal response available.'},
      {title:'Universe Tankships v ITWF [1983]',example:'The House of Lords considered illegitimate economic pressure and the practical absence of a reasonable alternative in economic duress.',demonstrates:'Commercial pressure is not automatically unlawful. The law asks whether the pressure crossed the line into illegitimate compulsion.'},
      {title:'Hadley v Baxendale [1854]',example:'The case established a foundational approach to remoteness of contractual damages by asking whether loss arose naturally or was within the parties’ reasonable contemplation.',demonstrates:'A breach does not make every later loss recoverable. Remedies are limited by legal rules linking loss to the contract and what could reasonably have been contemplated.'}
    ],
    'human-rights-framework': [
      {title:'A v Secretary of State for the Home Department [2004]',example:'The House of Lords held that indefinite detention provisions for certain foreign terrorism suspects were incompatible with Convention rights and discriminatory in operation.',demonstrates:'Human-rights adjudication can require courts to examine whether serious state interference is justified, proportionate and applied consistently.'},
      {title:'R (Daly) v Secretary of State for the Home Department [2001]',example:'The House of Lords held that a prison policy allowing officers to examine legally privileged correspondence in prisoners’ absence went further than necessary.',demonstrates:'Proportionality asks whether interference with a protected interest is justified and no more intrusive than necessary to achieve a legitimate aim.'},
      {title:'Campbell v MGN Ltd [2004]',example:'The House of Lords balanced Naomi Campbell’s privacy interests against freedom of expression after publication of information and photographs about treatment for drug addiction.',demonstrates:'Rights can conflict. Courts may need to balance privacy and expression rather than treating either right as absolute.'}
    ],
    'law-evaluation': [
      {title:'R v R [1991]',example:'The House of Lords confirmed that the historic marital exemption from rape could no longer stand in modern law.',demonstrates:'Common law can develop as social and legal understandings change, raising questions about judicial development, certainty and the relationship between law and morality.'},
      {title:'Human Rights Act 1998',example:'The Human Rights Act requires courts, so far as possible, to interpret legislation compatibly with Convention rights and allows declarations of incompatibility where that cannot be achieved.',demonstrates:'Evaluation of substantive law can include effectiveness, rights protection, parliamentary sovereignty and the constitutional role of judges.'},
      {title:'Offences Against the Person Act 1861',example:'Modern courts still apply offences drafted in the nineteenth century to contemporary violence.',demonstrates:'A law can remain operational while attracting criticism about language, structure and accessibility. Evaluation should distinguish practical function from the quality of legal design.'}
    ]
  },
  history: {
    'us-government': [
      {title:'Brown v Board of Education (1954)',example:'The US Supreme Court held that racial segregation in public schools was unconstitutional.',demonstrates:'Federal courts can drive constitutional change even where state governments resist, showing why the separation of federal and state power matters to historical explanation.'},
      {title:'Little Rock, 1957',example:'President Eisenhower sent federal troops to enforce school desegregation at Central High School in Little Rock after resistance by Arkansas authorities.',demonstrates:'Federalism can produce conflict between state and federal authority. Presidential power may become decisive when constitutional rulings are resisted locally.'},
      {title:'Congress and the Civil Rights Act 1964',example:'Congress passed, and President Johnson signed, major federal legislation prohibiting discrimination in important areas of public life and employment.',demonstrates:'Change can depend on interaction between executive leadership, Congress, courts, campaigning and wider political conditions.'}
    ],
    'civil-rights': [
      {title:'Plessy v Ferguson (1896)',example:'The Supreme Court upheld racial segregation under the “separate but equal” doctrine.',demonstrates:'The period begins with powerful legal support for segregation, providing a benchmark against which later constitutional and legislative change can be judged.'},
      {title:'Brown v Board of Education (1954)',example:'The Supreme Court rejected segregated public schooling as unconstitutional.',demonstrates:'Brown was a major legal turning point, but implementation difficulties show why formal legal change and lived experience must be distinguished.'},
      {title:'Civil Rights Act 1964 and Voting Rights Act 1965',example:'These federal laws attacked discrimination and barriers to political participation during the high point of the modern civil-rights movement.',demonstrates:'Legislation can accelerate change when campaigning, federal leadership and political opportunity align, while later inequalities remind historians to examine continuity as well as achievement.'}
    ],
    'superpower': [
      {title:'Spanish-American War, 1898',example:'US victory over Spain expanded American influence overseas, including control of Puerto Rico and the Philippines and a dominant role in Cuba.',demonstrates:'The war marks an important stage in the growth of US overseas power and challenges a simple picture of nineteenth-century isolation.'},
      {title:'Marshall Plan, 1947',example:'The United States provided large-scale economic assistance to rebuild European economies after the Second World War.',demonstrates:'Superpower status rested on economic and diplomatic capacity as well as military strength, and the US used that capacity to shape the post-war order.'},
      {title:'Cuban Missile Crisis, 1962',example:'The confrontation over Soviet missiles in Cuba brought the United States and Soviet Union close to nuclear conflict.',demonstrates:'Global influence also created global risk. Military, diplomatic and presidential decision-making all mattered to how US power operated during the Cold War.'}
    ],
    'breadth-judgement': [
      {title:'Civil-rights change across 1890–1990',example:'A comparison from Plessy v Ferguson in 1896 through Brown in 1954 and the federal civil-rights legislation of the 1960s shows major legal change across the century.',demonstrates:'Breadth judgement comes from comparing the scale, pace and durability of change across periods rather than treating one famous event as the whole explanation.'},
      {title:'Foreign-policy change across the century',example:'The USA moved from late nineteenth-century expansion through two world wars into sustained Cold War global leadership.',demonstrates:'Chronology is evidence. Dividing a long period into meaningful phases allows a historian to test whether change was gradual, episodic or driven by turning points.'},
      {title:'Great Depression and Second World War',example:'The economic crisis of the 1930s and mobilisation for the Second World War transformed federal activity, production and the United States’ international position.',demonstrates:'Turning points can affect several themes at once. Their significance should be judged by the scale and persistence of consequences.'}
    ],
    'whig-reform': [
      {title:'Poor Law Amendment Act 1834',example:'The 1834 legislation reorganised poor relief around unions and workhouses and reflected strong concern with cost, administration and deterrence.',demonstrates:'Reform can combine humanitarian claims, administrative efficiency and social control. Historical evaluation should test motives against implementation and experience.'},
      {title:'Factory Act 1833',example:'The Act restricted child labour in textile factories and introduced a factory inspectorate.',demonstrates:'Government involvement in social conditions increased, but limited coverage and enforcement mean reform should be judged by practical effect as well as statutory intention.'},
      {title:'Municipal Corporations Act 1835',example:'The Act reformed many borough corporations and introduced more standardised elected municipal government.',demonstrates:'Whig reform included political and administrative change as well as social legislation, supporting analysis of a wider reforming programme.'}
    ],
    chartism: [
      {title:'People’s Charter, 1838',example:'The People’s Charter set out six political demands including universal male suffrage, secret ballots and payment of MPs.',demonstrates:'Chartism had a recognisable political programme, allowing historians to compare its aims with both its immediate achievements and later reforms.'},
      {title:'Newport Rising, 1839',example:'Thousands of Chartist supporters marched on Newport in South Wales; soldiers fired on the crowd and leading Chartists were later tried.',demonstrates:'Chartism included tension over methods and faced determined state resistance. Regional events in Wales were central to the movement’s national story.'},
      {title:'Chartist petitions, 1839, 1842 and 1848',example:'Mass petitions repeatedly presented Chartist demands to Parliament, but the Commons rejected them.',demonstrates:'Large-scale mobilisation did not translate into immediate parliamentary success, helping distinguish popular support from political power and long-term significance.'}
    ],
    'protest-wales-england': [
      {title:'Rebecca Riots, c.1839–1843',example:'Protesters in west and mid Wales attacked tollgates while expressing grievances about road tolls and wider rural economic pressures.',demonstrates:'Local economic grievances, symbolic targets and regional conditions can shape protest methods and support.'},
      {title:'Plug Plot disturbances, 1842',example:'During the 1842 general strike, workers in parts of industrial Britain stopped machinery by removing boiler plugs as economic and political protest spread.',demonstrates:'Economic distress and political demands could overlap, and protest methods could move beyond petitions into direct action.'},
      {title:'Anti-Corn Law League',example:'The League used organised campaigning, publications, public meetings and electoral pressure before the Corn Laws were repealed in 1846.',demonstrates:'Different reform movements used different resources and strategies. Organisation, funding, political access and clarity of aims can affect outcomes.'}
    ],
    'source-evaluation': [
      {title:'The Northern Star',example:'The Northern Star was a major Chartist newspaper founded in 1837 and associated with Feargus O’Connor.',demonstrates:'A partisan source can be extremely valuable for understanding Chartist arguments, priorities and mobilisation. Its political purpose shapes what it reveals rather than making it automatically useless.'},
      {title:'Parliamentary reports',example:'Nineteenth-century parliamentary commissions and reports gathered evidence on issues such as factories, mines and poverty.',demonstrates:'Official provenance can provide detailed contemporary evidence, but historians must still consider who collected testimony, why it was collected and whose voices were included.'},
      {title:'Chartist petitions',example:'The petitions presented to Parliament record formal demands and claims of mass support.',demonstrates:'The value of a source depends on the enquiry. A petition is strong evidence for declared aims and mobilisation, but it cannot by itself prove the views of every signatory.'}
    ],
    'nea-process': [
      {title:'A published historian’s interpretation',example:'A scholarly history normally makes an argument from selected primary and secondary evidence and places that argument within a wider historical debate.',demonstrates:'The NEA should evaluate what an historian argues, what evidence supports that interpretation and how it compares with alternatives, rather than treating quotations as self-proving.'},
      {title:'A primary-source archive record',example:'A contemporary letter, speech, government record, newspaper or image can provide direct evidence from the period when its provenance and context are understood.',demonstrates:'Strong historical enquiry records source details immediately and distinguishes what a source reveals from what later historians infer from it.'},
      {title:'WJEC authentication requirements',example:'The NEA is formally assessed and must remain the learner’s own work under school and awarding-body authentication arrangements.',demonstrates:'Organisation tools can support research logs, deadlines and source management, but the historical argument and submitted prose must remain Kellyn’s own.'}
    ]
  },
  'welsh-bacc': {
    'question-rationale': [
      {title:'Public Health Wales as a topic source',example:'Public Health Wales publishes evidence on health and wellbeing issues affecting people and communities in Wales.',demonstrates:'A viable project topic can be grounded in a real issue with accessible evidence, but the final question still needs to be focused, ethical and manageable.'},
      {title:'Transport for Wales data and plans',example:'Transport for Wales publishes information about rail, bus and transport programmes that can support investigation of real transport questions.',demonstrates:'A genuine organisation can provide useful context and evidence, while the project question must remain narrow enough for Kellyn to analyse rather than merely describe.'},
      {title:'Supervisor approval',example:'The Individual Project process requires school supervision and approval within the qualification’s assessment arrangements.',demonstrates:'Feasibility is not only an academic judgement. Time, ethics, access and formal assessment requirements all shape whether a proposed investigation is workable.'}
    ],
    'research-plan': [
      {title:'Welsh Government open data',example:'Welsh Government and StatsWales provide datasets across education, population, economy, health and communities.',demonstrates:'Planning should begin with the evidence needed to answer the question. Knowing that suitable data exists can affect methods, milestones and feasibility.'},
      {title:'A staged research timetable',example:'Real research projects commonly separate scoping, evidence collection, analysis, review and final communication rather than treating research as one continuous writing task.',demonstrates:'Milestones make dependencies visible and create time to respond when access, evidence or methods do not work as expected.'},
      {title:'Formal supervisor meetings',example:'The Individual Project includes formal supervision and records of project development as part of the assessed process.',demonstrates:'A research plan must include required checkpoints and evidence of progress, not only a final submission date.'}
    ],
    'source-evaluation-ip': [
      {title:'ONS statistical releases',example:'The Office for National Statistics publishes methodologies alongside many datasets and statistical releases.',demonstrates:'Credibility can be assessed through transparency about methods, definitions and limitations rather than relying only on the reputation of a website.'},
      {title:'Senedd Research',example:'Senedd Research publishes impartial briefings for the Welsh Parliament on public-policy issues.',demonstrates:'A source can be highly relevant to Welsh issues while still needing evaluation for date, scope, evidence base and the exact question Kellyn is investigating.'},
      {title:'Campaign organisation material',example:'A campaigning organisation may publish strong evidence while also seeking to persuade readers towards a particular policy position.',demonstrates:'Bias does not make a source unusable. It means purpose, evidence selection and alternative sources must be considered when judging what the source can support.'}
    ],
    'analyse-evidence': [
      {title:'Comparing official and survey evidence',example:'An official administrative dataset and a public-opinion survey can describe the same issue differently because they measure different things.',demonstrates:'Analysis requires asking why evidence agrees or differs, what each source measures and what conclusions can reasonably be drawn from the combination.'},
      {title:'Welsh Government and third-sector evidence',example:'A policy report and a charity’s service-user evidence may focus on different populations, outcomes or time periods.',demonstrates:'Synthesis is not copying several summaries together. It means comparing evidence, explaining differences and deciding what each source contributes to the project question.'},
      {title:'Missing data',example:'A dataset may exclude a group, use a broad category or stop before the most recent period Kellyn wants to study.',demonstrates:'Recognising a limitation is part of analysis. The conclusion should be no stronger than the evidence available.'}
    ],
    'produce-review': [
      {title:'Reference audit',example:'Academic and professional reports normally retain enough bibliographic information for a reader to identify and check the evidence used.',demonstrates:'A final review should verify that claims can be traced to sources and that source details collected during research have been used consistently.'},
      {title:'Version and evidence trail',example:'Research projects often keep dated drafts, decisions, meeting records and source logs to show how work developed.',demonstrates:'Authentication and reflection are strengthened by a clear process trail. The final product should be visibly connected to Kellyn’s own research decisions and development.'},
      {title:'WJEC authentication',example:'The Individual Project is assessed work and must comply with awarding-body and school authentication requirements.',demonstrates:'AI can support learning, organisation and checking the process, but it must not replace Kellyn’s own assessed analysis or writing.'}
    ]
  }
}

export function examplesFor(subjectSlug, topicSlug) {
  return EXAMPLES[subjectSlug]?.[topicSlug] || []
}

export function exampleFor(subjectSlug, topicSlug, index=0) {
  const rows = examplesFor(subjectSlug, topicSlug)
  return rows.length ? rows[index % rows.length] : null
}
