export const SOCIOLOGY_REAL_WORLD_EXAMPLES = {
  'crime-social-construction': [
    {title:'Legal definitions change over time',example:'The Sexual Offences Act 1967 partially decriminalised private consensual sexual acts between men over 21 in England and Wales. Later legal reforms changed the age threshold and extended equality protections further.',demonstrates:'Crime and deviance are socially and historically located. Conduct can move between criminal, deviant, tolerated and accepted categories as laws and social norms change.'},
    {title:'Social construction in practice',example:'The treatment of same-sex relationships across twentieth- and twenty-first-century Britain shows that an act can be legally prohibited in one period and lawful in another without the underlying behaviour itself changing.',demonstrates:'A social-construction approach asks how rules are made, whose values shape them and why definitions differ between times, places and groups.'},
    {title:'Becker and the Edinburgh Study',example:'Howard Becker argued that deviance depends partly on the successful application of a label. The Edinburgh Study of Youth Transitions and Crime found that formal justice intervention could stigmatise young people and that official convictions did not simply mirror self-reported offending.',demonstrates:'Labelling is not only a theory about names. Criminal justice contact can change how people are treated and may become part of the process that shapes later behaviour and official records.'},
    {title:'Cohen: Mods, Rockers and moral panic',example:'Stanley Cohen studied media and public reactions to clashes involving Mods and Rockers at English seaside towns in the 1960s. He showed how selection, exaggeration and repeated reporting could construct folk devils and amplify public concern.',demonstrates:'Media can become part of the social reaction to deviance rather than simply reporting it. Moral-panic theory is strongest when the scale and form of the reaction are compared with the underlying behaviour.'}
  ],
  'crime-patterns-measurement': [
    {title:'CSEW and police-recorded crime, 2026',example:'ONS Crime in England and Wales for the year ending March 2026 combines the Crime Survey for England and Wales with police-recorded crime. The CSEW asks people about victimisation whether or not incidents reached the police, while police data only include offences known to and recorded by police.',demonstrates:'No single source is a complete count of crime. Sociologists must identify what each dataset measures before comparing trends or explaining patterns.'},
    {title:'Shoplifting and reporting changes',example:'Police recorded 507,086 shoplifting offences in the year ending March 2026. ONS warned that recent changes reflect both offending and improved reporting by retailers following closer work with police.',demonstrates:'A movement in police-recorded crime can be produced by changes in reporting and recording as well as changes in underlying offending. Official statistics need interpretation rather than simple repetition.'},
    {title:'Cardiff Model and the hidden figure',example:'Research behind the Cardiff Model compared emergency-department information about violent injury with police records. Early work found that only about 23% of violent incidents seen in emergency departments appeared in police records.',demonstrates:'Alternative data sources can reveal serious incidents missing from police statistics. This is a clear real-world example of the hidden figure of crime and the value of triangulating sources.'},
    {title:'Edinburgh Study self-report evidence',example:'The Edinburgh Study repeatedly asked a cohort of around 4,300 young people about their own offending and compared answers with official records. Self-report data gave a much fuller picture of delinquency than official criminal justice records alone.',demonstrates:'Self-report studies can uncover undetected offending and challenge stereotypes produced by official statistics, although honesty, recall and attrition still affect validity.'}
  ],
  'crime-theories': [
    {title:'Durkheim: crime as normal',example:'Durkheim argued that some deviance is inevitable in every society and can perform functions such as boundary maintenance and social change. His deliberately provocative phrase that crime is “normal” refers to its sociological presence and functions, not moral approval.',demonstrates:'Functionalism looks beyond individual offenders to ask how deviance may contribute to social regulation, shared boundaries and change.'},
    {title:'Merton, strain and Welsh poverty',example:'Welsh Government data for financial years ending 2023 to 2025 estimated that 22% of people in Wales lived in relative income poverty after housing costs. Merton’s strain theory asks what happens when culturally valued goals such as material success are promoted while legitimate opportunities remain unequal.',demonstrates:'Current poverty data provide a real structural context in which strain theory can be evaluated. The statistic does not prove that poverty causes crime; it helps test whether unequal opportunity makes the theory plausible.'},
    {title:'Youth offending patterns and subculture',example:'Youth Justice Board statistics for 2024/25 show that 86% of children receiving a caution or sentence were boys and 76% were aged 15 to 17. These are strong age and gender patterns within formal youth justice.',demonstrates:'Subcultural theories can be applied to peer groups, status, masculinity and access to legitimate or illegitimate opportunities. The statistics identify a pattern; theories must explain why it occurs.'},
    {title:'Southern Water and corporate crime',example:'In July 2026 Southern Water was fined £7.1 million for repeated illegal sewage pollution after preventable equipment failures and poor operational oversight. The company had previously received a £90 million pollution fine in 2021.',demonstrates:'Marxist approaches broaden attention beyond visible street crime to offending and harm involving powerful organisations. The example supports questions about regulation, profit, power and which crimes attract public attention.'},
    {title:'Stop and search and interactionism',example:'Ministry of Justice data for 2024/25 show Black people accounted for 13% of stop and searches in England and Wales, compared with around 4% of the population in the Census comparison used by the report. The report also notes geography and offence mix as important contextual factors.',demonstrates:'Interactionists such as Cicourel ask how suspicion, discretion and typifications shape who becomes visible to criminal justice agencies. Disproportionality is evidence to investigate, not proof of one single cause.'},
    {title:'Realism in practice: vehicle security and Cardiff',example:'Home Office research linked improved vehicle security, including electronic immobilisers, to a substantial share of the long-term fall in vehicle theft. The Cardiff Model instead combines health, police and local-authority data to identify violence hotspots and target prevention.',demonstrates:'Right realism is illustrated by target hardening and opportunity reduction, while left realism is illustrated by practical victim-focused prevention combined with attention to communities and social context.'},
    {title:'Gendered crime and victimisation',example:'The Crime Survey for England and Wales estimated that in the year ending March 2025 about 9.1% of women and 6.5% of men experienced domestic abuse. Police data from 32 forces showed 72.1% of victims of domestic-abuse-related crimes were female.',demonstrates:'Feminist criminology directs attention to gendered victimisation, private-sphere violence and control rather than treating male street offending as the default subject of criminology. Male victimisation must still remain visible in the analysis.'}
  ],
  'crime-policy-evaluation': [
    {title:'Electronic immobilisers and situational prevention',example:'Home Office research concluded that vehicle crime fell around 80% from its 1995 peak and estimated electronic immobilisers contributed around 25% to 50% of the decline in stolen vehicles to 2013.',demonstrates:'Situational crime prevention can reduce opportunities without changing offender values. Policy evaluation should still consider displacement, adaptation and whether effects persist.'},
    {title:'Cardiff Model: evaluating more than one outcome',example:'Evaluation of the Cardiff Model found a significant reduction in serious violence-related hospital admissions compared with similar cities, while police recording of less serious assaults increased.',demonstrates:'A policy can reduce serious harm even when one recorded-crime measure rises. Strong evaluation uses several outcomes and asks what each source actually measures.'},
    {title:'Youth diversion and desistance',example:'The Edinburgh Study found appropriately targeted diversionary strategies were associated with increased desistance from serious offending. Youth Justice Board data also show the number of children cautioned or sentenced in 2024/25 was around 65% lower than ten years earlier.',demonstrates:'Diversion fits labelling theory because it can avoid unnecessary formal criminalisation. Falling formal sanctions should not automatically be interpreted as an identical fall in offending.'}
  ],
  'methods-design': [
    {title:'British Social Attitudes: real survey design',example:'The British Social Attitudes survey has tracked attitudes since 1983 using probability-based sampling and repeated questions. Its design aims to make stronger claims about the British population than an open voluntary online poll can support.',demonstrates:'A research design should be chosen to match the research aim. Standardisation, sampling and repeated measurement make trends more comparable over time.'},
    {title:'Operationalisation can change the statistic',example:'ONS redesigned the Crime Survey for England and Wales questions used to measure domestic abuse from the year ending March 2024. ONS warns that the new estimates cannot be directly compared with the previous series because the questions and measurement changed.',demonstrates:'Operationalisation affects the data produced. Turning an abstract concept into questions and indicators is a methodological decision with consequences for validity and comparability.'},
    {title:'Mixed methods in the Edinburgh Study',example:'The Edinburgh Study combined repeated self-report questionnaires, interviews and administrative records from education, social work and criminal justice across many years.',demonstrates:'Different methods produce different kinds of evidence. Combining them can deepen understanding and allow researchers to compare sources, although the design becomes more expensive and complex.'},
    {title:'Random sampling and non-response',example:'NatCen selects British Social Attitudes addresses using random probability methods, but selected people do not all participate. Non-response weighting is therefore used to reduce the effect of unequal participation.',demonstrates:'A probability sample can still become biased through non-response. Weighting is a methodological response to that problem, not proof that all bias has disappeared.'},
    {title:'Longitudinal research and triangulation',example:'The Edinburgh Study followed roughly 4,300 people over time and linked repeated self-reports with official administrative data. This allowed researchers to compare changes within the same cohort and test whether different sources told similar stories.',demonstrates:'Longitudinal designs are strong for studying change and sequence, while triangulation can improve understanding. Attrition, cost and changing measurement remain important limitations.'},
    {title:'Natsal and informed consent',example:'The National Survey of Sexual Attitudes and Lifestyles researches highly sensitive topics. Participants can refuse biological samples, and separate permission is requested before survey responses are linked to administrative records.',demonstrates:'Ethics must be applied to the exact research activity. Consent, privacy, sensitive disclosure and data linkage require specific safeguards rather than a generic statement that research is “confidential”.'}
  ],
  'inequality-patterns': [
    {title:'Poverty in Wales',example:'Welsh Government data for financial years ending 2023 to 2025 estimated that 22% of people in Wales lived in relative income poverty after housing costs. A newer measure estimated 10% of children were in deep material poverty in financial years ending 2024 to 2025.',demonstrates:'Social inequality affects material life chances in contemporary Wales. A percentage describes the pattern; sociology still has to explain why the inequality is produced and maintained.'},
    {title:'Wealth inequality in Great Britain',example:'ONS Wealth and Assets Survey data for April 2020 to March 2022 estimated median household wealth at £293,700. The wealthiest 10% had £1,200,500 or more, while the least wealthy 10% had £16,500 or less.',demonstrates:'Wealth is not the same as income. Property, pensions and other assets accumulate over time and can create class differences that annual earnings alone do not reveal.'},
    {title:'Gender pay gap, 2025',example:'ONS reported that the UK full-time employee gender pay gap was 6.9% in April 2025, down from 7.1% in 2024. Welsh data also show a long-term narrowing of the full-time gender pay difference.',demonstrates:'Gender inequality can persist while changing over time. The pay gap is a population pattern and does not by itself prove unequal pay for identical work; occupational segregation, caring, progression and discrimination all require analysis.'},
    {title:'Ethnic inequality in Wales',example:'Welsh Government reporting for 2024 found Black, Asian and Minority Ethnic employees in Wales earned on average 3.6% less per hour than White employees, while warning that the series is volatile because of sample size and year-to-year variation.',demonstrates:'Ethnic inequality needs careful disaggregation and methodological caution. A broad category can hide differences between groups, and a short-term estimate should not be treated as a complete explanation.'},
    {title:'Young people and NEET rates in Wales',example:'Welsh Government estimated that 17.0% of 16 to 24 year olds in Wales were not in education, employment or training in the year ending December 2025, with variation by disability, ethnicity and region.',demonstrates:'Age shapes exposure to labour-market and education risks. Intersectionality matters because age interacts with disability, ethnicity and place.'}
  ],
  'inequality-theories': [
    {title:'Persistent Welsh life-chance inequalities',example:'ONS data for 2022 to 2024 show male life expectancy at birth in the most deprived Welsh areas was 73.6 years compared with 81.9 years in the least deprived areas. Healthy life expectancy showed an even larger gap.',demonstrates:'Theories of inequality can be tested against concrete life chances. Material position remains associated with outcomes as fundamental as health and longevity.'},
    {title:'Testing Davis and Moore',example:'Davis and Moore argue that unequal rewards help society fill roles requiring scarce skills or lengthy training. Comparing pay and status across care workers, teachers, nurses, finance professionals and senior executives raises the question of whether rewards really correspond to social importance.',demonstrates:'Functionalism provides a possible social function for inequality, but real occupational rewards allow the theory to be tested rather than simply repeated.'},
    {title:'Marxism and wealth concentration',example:'Marx and Engels famously described history in terms of class struggles. Modern ONS data show the wealthiest tenth of Great British households held at least £1.2 million in household wealth in the latest detailed distribution release, compared with £16,500 or less for the least wealthy tenth.',demonstrates:'Persistent concentration of wealth gives contemporary material for Marxist analysis of ownership and economic power. The figures support evaluation of class inequality but do not prove every claim made by Marxism.'},
    {title:'Weber: market position, status and power',example:'Weber argued that class situation is closely connected to market situation, but also distinguished status and organised political power. Two people can therefore have similar incomes yet very different job security, professional prestige, credentials, pensions, networks or influence.',demonstrates:'Weber offers a multidimensional explanation of inequality. Economic position matters, but it does not exhaust differences in status and power.'},
    {title:'Feminism: work, power and safety',example:'In 2025 the UK full-time gender pay gap remained 6.9%, while the Crime Survey for England and Wales also showed women were more likely than men to experience domestic and partner abuse. These patterns sit in different social spheres but both concern gendered power and life chances.',demonstrates:'Feminist analysis links paid work, unpaid responsibilities, safety and power. Gender inequality cannot be reduced to one statistic or one institution.'},
    {title:'New Right and postmodernism under pressure from current evidence',example:'Welsh poverty data show employment reduces poverty risk but does not eliminate it: 22% of children in households where all adults worked were still in relative income poverty in the latest three-year estimate. At the same time, major deprivation gaps in Welsh life expectancy remain.',demonstrates:'Current evidence can both support and challenge theory. Employment matters, as New Right approaches predict, but in-work poverty points to structural limits; persistent health inequalities also challenge claims that material class has become unimportant in a more fragmented postmodern society.'}
  ]
}
